### PR TITLE
fix: `ERROR Cannot set property 'requiresBuild' of undefined`

### PR DESCRIPTION
**Pull request by vjpr**
#1217

### CODE REVIEW

**Comment by zkochan** [comment]
it would be nice to cover this with test. I am not 100% sure this is the right solution because it seems like requires build will be not sent for a dependency in shrinkwrap file.

I guess this happens when a direct dependency has a resolved dep and needs to be built and `shared-workspace-shrinkwrap` is `true`

**Comment by vjpr** [comment]
This is blocking me from rolling out `shared-workspace-shrinkwrap` to my team. Would it be okay to merge as a workaround?

**Comment by zkochan** [comment]
I will try to find the cause of this issue and cover it with a test.

I think this happens when prune removes the node that has a pending build

prune happens here:

https://github.com/pnpm/pnpm/blob/c204ff727a5adff721f14780d1b25795c7ab2d4b/packages/supi/src/install/updateShrinkwrap.ts#L47

**Comment by zkochan** [comment]
I think your solution is correct.

Unfortunately, I could not create a test for this yesterday. It would be great if you could reproduce it with some open-source packages or create some mocks in https://github.com/pnpm/pnpm-registry-mock

If no, I will merge it tonight as is, with some comments added.

**Pull request merged**
