### PR TITLE
feat(interactive-update): group dependancies by type, add package url column

### PR DESCRIPTION
**Pull request by th3fallen**
Partially resolves https://github.com/pnpm/pnpm/issues/6314

Notes:
- I really hate how the table rows are generated as it makes it nearly impossible to segment by dependency type while preserving column widths.

### CODE REVIEW

**Comment by th3fallen** [comment]
Have i mentioned my hatred for the whitespace strictness in those tests 😆 fix pushed

**Comment by zkochan** [comment]
When I run this on the pnpm repo, I see many duplications of the same package and also some empty lines

image

**Comment by th3fallen** [comment]
you ran it in the root of the repo?

**Comment by th3fallen** [comment]
Pushed an update that now properly dedupes but allows duplicates if the version are not the same (from prior behavior) also added a "workspace" column if workspaces are enabled to give an idea of where each package is coming from.

**Comment by zkochan** [comment]
ok, I'll review later.

**Pull request merged**
