### PR TITLE
feat: using FUSE to mount node_modules

### PR DESCRIPTION
**Pull request by zkochan**

### CODE REVIEW

**Review by Countrygrl00 — APPROVED** [review]

**Comment by rafaelliu** [comment]
Hi, zkochan I see some recent commits on `mount-modules`, do you still have plans to ship it? Looks like `fuse-native` has been dead for a couple of years and is not working on latest macs

**Comment by zkochan** [comment]
It is shipped. But I don't plan currently to fix fuse-native or anything.

**Comment by rafaelliu** [comment]
I did not realize that. Are there any documentations besides the README.md? It seems to be a fairly independent from pnpm, briefly mentioned in [its docs](https://pnpm.io/npmrc)

**Comment by zkochan** [comment]
The only docs are the readme.

**Pull request merged**
