### PR TITLE
chore(ci): setup windows github action

### PR DESCRIPTION
**Pull request by shellscape**
This implements a Github Action for a Windows workflow for PRs, and pushes to `master`. This mimics the setup from the appveyor config. Chose Node v14 as the target because it's exponentially faster on Windows and should help with run time.

### CODE REVIEW

**Comment by zkochan** [comment]
How to cache everything in the storage directory?

**Comment by shellscape** [comment]
I haven't really looked into caching on the windows builds because they've just kind of been an afterthought, something we run "just to make sure." I'll make a note to look into that for pnpm though.

**Comment by zkochan** [comment]
Seems like Verdaccio sometimes fails. Maybe it cannot get the packages from the registry. On travis, the verdaccio storage is cached. Probably that's why it is more stable

**Comment by zkochan** [comment]
alternatively, we could commit the storage to the repository

**Comment by zkochan** [comment]
ok, I think I will pack it to a tarball and unpack before the tests run

**Pull request merged**
