### PR TITLE
fix: avoid empty cloned files in Windows

### PR DESCRIPTION
**Pull request by nachoaldamav**

### CODE REVIEW

**Comment by Hazmi35** [comment]
Hi. sorry to ask, what's the status of cloning in ReFS?

**Comment by nachoaldamav** [comment]
> Hi. sorry to ask, what's the status of cloning in ReFS?

This PR should fix the issues in ReFS, waiting for it to be approved.

**Comment by zkochan** [comment]
CI fails on Windows.

**Review by zkochan — APPROVED** [review]

**Comment by Hazmi35** [comment]
Sorry for the bump, but it seems that the cloning fails if you're two levels deep of directory in ReFS and the package name is long:

`F:\one`
image

`F:\one\two`
image

**Comment by nachoaldamav** [comment]
Yeah I saw it too, fixed it in another update, it was an error when trying to check the drive compatibility with reflinks. 
Thanks @Hazmi35

**Comment by nachoaldamav** [comment]
Btw, @Hazmi35 Do you see any perf problem when using cloning, like if the process gets stuck in the middle of the installation, I don't know if it's a problem in my PC or if something is wrong in my implementation

**Comment by Hazmi35** [comment]
I haven't experienced it

**Pull request merged**
