### PR TITLE
feat: pnpm should fail if the project needs another version

### LINKED ISSUE #1382: Examine 'engines.pnpm' in package.json
### Code to reproduce the issue:

**Step 1:** Create `package.json` with the following content

```json
{
  "private": true,
  "version": "0.0.0",
  "engines": {
    "pnpm": ">= 99999.0.0"
  }
}
```

**Step 2:** Run `pnpm install ...`

### Expected behavior:

pnpm should at least warn user for not using demanded version.

### Actual behavior:

pnpm goes ahead and installs dependencies anyway

### Why?

* pnpm can be used to manage monorepo.
* Different pnpm versions might provide different monorepo features.
* Different monorepos might demand different features from pnpm.

### PR DESCRIPTION
**Pull request by zkochan**
pnpm should fail if the project has an engines.pnpm field in its
package.json and the running pnpm's version does not satisfy the
range.

pnpm should also fail it the project has an engines.node field
and process.version does not satisfy it.

close #1382

### CODE REVIEW

**Comment by Ten0** [comment]
Owkay so I'm using node >10 to run packages that were designed for node 10 and more, and due to this change I can't install them anymore. How do we declare multiple compatible major versions in "engines" ?

**Comment by zkochan** [comment]
you have `"engines": {"node": ">10"}` in `package.json` and it started failing?
Can you create a repo to reproduce?

**Comment by Ten0** [comment]
Thanks, that indeed is the right syntax. :)
I still have a need for packages that I don't own where the maintainer does not guarantee >11 compatibility to not have to install node 10 on my machine. Is there a bypass switch for this ?
If not, shouldn't we add one ?

**Comment by zkochan** [comment]
Packages that you don't own? You mean dependencies inside node_modules? Those don't cause installations to fail unless you set the `engine-strict` config to `true`

**Comment by Ten0** [comment]
This behaviour is indeed mentionned in the documentation.
However I mean non-dependencies (a project workspace -~100 packages- I install using pnpm that is regularly updated so I can't just patch them everytime nor have them unclean in my git tree).

**Comment by zkochan** [comment]
hm, I guess we can make this check a warning when engine-strict is false. But only the `engines.node` check

**Comment by Ten0** [comment]
That would perfectly fit with my scenario! :)

**Pull request merged**
