### PR TITLE
fix: '--unknown.option value' should works fine

### PR DESCRIPTION
**Pull request by fireairforce**
closes: https://github.com/pnpm/pnpm/issues/4159

### CODE REVIEW

**Comment by fireairforce** [comment]
fixed the issue and the case like that: 
image

Actually the useage on the website was wrong, it will treat `x64` as a dependencies...

**Comment by zkochan** [comment]
so `--config.target_arch=x64` works without changes? In that case, maybe let's just update the docs and not support custom settings without =

**Comment by fireairforce** [comment]
> #4159

yes, `--config.target_arch=x64` works fine,but i see there are some people be used to use the settings without `=`😅

**Comment by fireairforce** [comment]
> so `--config.target_arch=x64` works without changes? In that case, maybe let's just update the docs and not support custom settings without =

yes, --config.target_arch=x64 works fine,but i see there are some people be used to use the settings without `=` 😅

**Comment by gabrielhpugliese** [comment]
Hey, thanks for this work!
I was trying to find the specification of `getopts` to check if `--param X` is as valid as `--param=X` at least on `bash` and found [this experiment](https://stackoverflow.com/a/7680682) that shows that both are equally valid. So I would say it's a good idea to be able to support both.

**Comment by zkochan** [comment]
well, the known CLI options work without = but these custom config settings is just a workaround. I don't think we should complicate the codebase for this edge case scenario.

**Pull request closed without merging**
