### PR TITLE
feat: update version when pinnedVersion is *

### LINKED ISSUE #5681: when semver is wildcard,  package.json is not updated with exact version
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**
```json
{
  "typescript": "*"
}
```
after run `pnpm i typescript@latest`, the package.json still, expect to be `"typescript": "4.9.3"`
**Describe the solution you'd like**

when install with specified package, update the exact version repectively, like npm, i.e.
```
npm i typescript 
npm i typescript@latest

# both will update the package.json
{
  "typescript": "4.9.3"
}
```

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

### PR DESCRIPTION
**Pull request by HomyeeKing**
close #5681

### CODE REVIEW

**Comment by zkochan** [comment]
add a changeset

**Review by zkochan — APPROVED** [review]

**Comment by folknor** [comment]
Did this change cause pnpm to change my dependencies in package.json from for example:
```
  85   │     "devDependencies": {
  86   │         "@fortawesome/fontawesome-free": "latest",
  87   │         "@parcel/config-default": "nightly",
  88   │         "@parcel/core": "nightly",
  89   │         "@parcel/optimizer-cssnano": "nightly",
  90   │         "@parcel/optimizer-htmlnano": "nightly",
  91   │         "@parcel/optimizer-svgo": "nightly",
  92   │         "@parcel/packager-css": "nightly",
  93   │         "@parcel/packager-html": "nightly",
  94   │         "@parcel/packager-raw-url": "nightly",
  95   │         "@parcel/transformer-css": "nightly",
  96   │         "@parcel/transformer-html": "nightly",
  97   │         "@parcel/transformer-image": "nightly",
  98   │         "@parcel/transformer-js": "nightly",
  99   │         "@parcel/transformer-postcss": "nightly",
 100   │         "@parcel/transformer-posthtml": "nightly",
 101   │         "@parcel/transformer-sass": "nightly",
 102   │         "@parcel/transformer-webmanifest": "nightly",
 103   │         "@popperjs/core": "latest",
 104   │         "animate.css": "latest",
 105   │         "animated-scroll-to": "latest",
 106   │         "autoprefixer": "latest",
 107   │         "blueimp-gallery": "latest",
 108   │         "bootstrap": "latest",
 109   │         "browserslist": "latest",
 110   │         "browserslist-useragent-regexp": "latest",
 111   │         "copyfiles": "latest",
 112   │         "dompurify": "latest",
 113   │         "fabric": "latest",
 114   │         "parcel": "nightly",
 115   │         "postcss": "latest",
 116   │         "postcss-preset-env": "latest",
 117   │         "rimraf": "latest",
 118   │         "sass": "latest",
 119   │         "sharp": "^0.31.2"

```

to

```
  85   │     "devDependencies": {
  86   │         "@fortawesome/fontawesome-free": "^6.2.1",
  87   │         "@parcel/config-default": "2.0.0-nightly.1223",
  88   │         "@parcel/core": "2.0.0-nightly.1221",
  89   │         "@parcel/optimizer-cssnano": "2.0.0-nightly.1223",
  90   │         "@parcel/optimizer-htmlnano": "2.0.0-nightly.1223",
  91   │         "@parcel/optimizer-svgo": "2.8.3-nightly.2846",
  92   │         "@parcel/packager-css": "2.0.0-nightly.1223",
  93   │         "@parcel/packager-html": "2.0.0-nightly.1223",
  94   │         "@parcel/packager-raw-url": "2.8.3-nightly.2846",
  95   │         "@parcel/transformer-css": "2.0.0-nightly.1223",
  96   │         "@parcel/transformer-html": "2.0.0-nightly.1223",
  97   │         "@parcel/transformer-image": "2.8.3-nightly.2846",
  98   │         "@parcel/transformer-js": "2.0.0-nightly.1223",
  99   │         "@parcel/transformer-postcss": "2.0.0-nightly.1223",
 100   │         "@parcel/transformer-posthtml": "2.0.0-nightly.1223",
 101   │         "@parcel/transformer-sass": "2.0.0-nightly.1223",
 102   │         "@parcel/transformer-webmanifest": "2.8.3-nightly.2846",
 103   │         "@popperjs/core": "^2.11.6",
 104   │         "animate.css": "^4.1.1",
 105   │         "animated-scroll-to": "^2.3.0",
 106   │         "autoprefixer": "^10.4.13",
 107   │         "blueimp-gallery": "^3.4.0",
 108   │         "bootstrap": "^5.2.3",
 109   │         "browserslist": "^4.21.4",
 110   │         "browserslist-useragent-regexp": "^4.0.0",
 111   │         "copyfiles": "^2.4.1",
 112   │         "dompurify": "^2.4.1",
 113   │         "fabric": "^5.3.0",
 114   │         "parcel": "2.0.0-nightly.1221",
 115   │         "postcss": "^8.4.20",
 116   │         "postcss-preset-env": "^7.8.3",
 117   │         "rimraf": "^3.0.2",
 118   │         "sass": "^1.57.1",
 119   │         "sharp": "^0.31.3"
 120   │     }

```

And if so, am I correct in that there's no way for me to prevent it?

**Comment by HomyeeKing** [comment]
@folknor 
it has nothing to do with this commit, it just handle the `none` case (such as `foo: *`), 
most of your deps are pinned as `major` through this function,
https://github.com/pnpm/pnpm/blob/main/packages/which-version-is-pinned/src/index.ts#L3

and it seems no way to avoid upgrading version, since it always updated
https://github.com/pnpm/pnpm/blob/main/pkg-manager/core/src/install/index.ts#L498

**Comment by folknor** [comment]
@HomyeeKing This behavior is not present in pnpm v7.17.1, but is present in 7.18, which is the first release with this pull request.

I've read through every other commit between 7.17.1 and 7.18, and the only other one that might be related is https://github.com/pnpm/pnpm/commit/f3bfa2aae65406935b58b05a1f34b047ff4cb301 as far as I can see.

**Comment by folknor** [comment]
@zkochan 7.24.2 still does this, can you read through my comments here and let me know if I should open a new issue about this? The way I see it (and of course my perspective could be completely wrong :smile: ) this is either (1) a regression, (2) something that should be a config setting, or (3) intended behavior that won't change.

Question is if it was caused by this pull request or not. I don't know. I just know what I wrote previously. I'm not sure how to test 7.18 without this pull locally.

**Comment by HomyeeKing** [comment]
@folknor  sorry, I will check the code this weekend, kind of busy recently 😅

**Comment by HomyeeKing** [comment]
@folknor  https://github.com/pnpm/pnpm/pull/5764/files#diff-d2d9ebb33dc9a2437d69f3c4c77d5e194a34b29dc80bce3a23a3aca0a45c4866L165

👆🏻this PR makes the difference

image

**Comment by folknor** [comment]
> @folknor https://github.com/pnpm/pnpm/pull/5764/files#diff-d2d9ebb33dc9a2437d69f3c4c77d5e194a34b29dc80bce3a23a3aca0a45c4866L165

Thank you! I disregarded that commit when I looked through the list because I presumed that it would only affect versions that had `workspace:` in them.

Do you think I should file a ticket or just comment on that PR referrencing the discussion here?

**Comment by HomyeeKing** [comment]
comment on that PR and describe your case

**Pull request merged**
