### PR TITLE
feat: specifying a path to workspace packages in version specs

### LINKED ISSUE #2959: Capability of specifying a path instead of "workspace:*"
I already explained the issue in [this issue](https://github.com/pnpm/pnpm/issues/2938#issuecomment-712413592). We "must" add all the packages to `pnpm-workspace.yaml` (even those that are generated). But for this to work. pnpm requires specifying a certain folder instead of `"workspace:*"`.

In short, I use babel to build the folder that includes all the packages (say `pkg`) and write the built packages to the dist-* folder (`dist-pkg`).

This means there will be two folders in the workspace that use the same name, and so, we need to specify a certain folder instead of `"workspace:*"`.

My suggestion is to calculate the path from the root of the workspace. So, something like this:
```
    "pkg1": "workspace:./dist-pkg/pkg1",
```

Normally, pnpm considers this:
```
    "pkg1": "workspace:./pkg/pkg1",
```

### PR DESCRIPTION
**Pull request by zkochan**
close #2959

### CODE REVIEW

**Comment by ExE-Boss** [comment]
This should probably also support `workspace:/packages/foo` as being relative to the workspace root, since that’s the root directory of a workspace.

**Comment by zkochan** [comment]
I am not sure. I like that syntax but I tried `file:/foo` with `npm install` and it searches for foo in the root of the disk. So it might be inconsistent.

**Comment by ExE-Boss** [comment]
That’s because `file:` is relative to the file system, whereas `workspace:` is relative to the workspace.

**Comment by zkochan** [comment]
Indeed, this sounds correct with pnpm's definition of "workspace"

Not so straightforward with Yarn... So if we do #2966, it might get confusing.

**Pull request merged**
