### PR TITLE
Increased stale duration from 10s to 20s

### LINKED ISSUE #594: Error: Unable to update lock within the stale threshold
### Code to reproduce
```
pnpm install
```

### Actual behavior:
**pnpm** starts to install packages in node_**modules/.resolutions** then fails with only 300 of them installed (1000 to be installed). **node.exe** process memory goes up to 800MB and exits with the following error.
Running the command again installs a few more packages each time (around 5). Please note that i have 11GB RAM free before running the command :)

```
C:\Users\aecz\AppData\Roaming\nvm\v6.9.4\node_modules\pnpm\lib\node_modules\proper-lockfile\index.js:180
    compromised = compromised || function (err) { throw err; };
                                                  ^
Error: Unable to update lock within the stale threshold
    at options.fs.utimes (C:\Users\aecz\AppData\Roaming\nvm\v6.9.4\node_modules\pnpm\lib\node_modules\proper-lockfile\index.js:108:66)
    at FSReqWrap.oncomplete (fs.js:123:15)
```
### Additional information:
[pnpm-debug.log.txt](https://github.com/pnpm/pnpm/files/744655/pnpm-debug.log.txt)

 - pnpm **0.50.0**
 - node **6.9.4**
 - Windows 7

### PR DESCRIPTION
**Pull request by aecz**
Fixes #594

### CODE REVIEW

**Comment by zkochan** [comment]
I wonder whether we need locks at all if they are so buggy

**Comment by andreypopp** [comment]
I think locks are needed — you do want two concurrent installations race to install the same package with `postinstall` hook for example — chances you end up with some broken state are big, I think.

**Comment by zkochan** [comment]
Merged

**Comment by aecz** [comment]
Did some more tests and it still fails sometimes with 20s stale. 30s seems better but i agree that it looks like a workaround not a real fix. I dont have problem with Yarn for example which i believe is using locks.

**Comment by zkochan** [comment]
Are you sure the problem is with the lock. I have some issues on Windows as well, when I install on really big projects. It seems like pnpm tries to do too much too quickly. I think we have to limit concurency using [throat](https://github.com/ForbesLindesay/throat).

**Comment by aecz** [comment]
Didnt had time to debug it and dont feel confident i can with this issue :) Im happy to do some test if you post them here. Here is one project which fails with pnpm. Fine with yarn and npm 3/4 but slow :(
[package.json.txt](https://github.com/pnpm/pnpm/files/748278/package.json.txt)

**Comment by zkochan** [comment]
Thanks, I will try to fix this because I have issues as well. Also if you have some quick questions/request, feel free to use the gitter chat https://gitter.im/pnpm/pnpm

**Comment by zkochan** [comment]
@aecz, please retry with pnpm@0.52.0. It is released under the next dist-tag

**Comment by aecz** [comment]
Thanks. ill reply on the issue page #594

**Pull request closed without merging**
