### PR TITLE
docs(README): suggest the most reliable installation

### PR DESCRIPTION
**Pull request by zkochan**
There are different ways to install pnpm but the easiest
and most reliable option is to use npm. So a new user should
use the method that we are most confident about.

### CODE REVIEW

**Comment by zkochan** [comment]
ok, now we are ready for the pnpm v5 hype 😆

**Comment by zkochan** [comment]
oh, that hurts but ok... 

I will change that message. Although for me `pnpm i -g pnpm` works fine. We do have many issues reported about `pnpm i -g`

**Comment by aparajita** [comment]
I have had issues installing pnpm with pnpm because the initial install with npm is still there. I can't remember the exact message, but it should work seamlessly.

**Comment by zkochan** [comment]
ok, I updated that message in the update notifier

**Pull request merged**
