### PR TITLE
feat: any unknown command is assumed to be a script

### LINKED ISSUE #2169: Add `pnpm SCRIPT` as a shortcut for `pnpm run SCRIPT`
It's quite convenient to hot have to type `run`. In case there could be a naming conflict, you could simply not make it available without `run`.

So turning `pnpm run build` into `pnpm build`.

### PR DESCRIPTION
**Pull request by zkochan**
close #2169

### CODE REVIEW

**Comment by ExE-Boss** [comment]
I think this should be configurable.

**Comment by zkochan** [comment]
Why? Just don't use it. Making it configurable is not easy because the
config read happens after the CLI args parsing.

ExE Boss <notifications@github.com> ezt írta (időpont: 2020. júl. 6., H
1:52):

**Comment by ExE-Boss** [comment]
I mean the `@pnpm/parse‑cli‑args` API should have an option to control whether `run` is allowed to be implicit, and potentially the name of the `run` command as well, instead of needing to create a custom `Set` where `has` returns `true` for all strings.

**Comment by zkochan** [comment]
`@pnpm/parse‑cli‑args` is the only place this can happen because it needs to validate the options. `pnpm foo --xxx` will be validated. So it will fail because `--xxx` is not a known option for `run`.

I can make the implicit command name configurable but I think `knownCommands` is still needed. Otherwise, how do I know which command does not exist?

**Pull request merged**
