### PR TITLE
fix: remove double wording in registries mismatch error message

### PR DESCRIPTION
**Pull request by gsong**

### CODE REVIEW

**Comment by zkochan** [comment]
Please describe your changes with changesets.

In the repo root, run `pnpx changesets`

**Comment by gsong** [comment]
@zkochan Sorry I didn't see this message earlier. For future reference, do you want the changesets  info in the PR description?

**Comment by gsong** [comment]
@zkochan Also, what do I need to do to make the command work?

```sh
$ pnpx changesets
Packages: +1
+
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/george/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Resolving: total 1, reused 1, downloaded 0, done
 WARN  changesets has no binaries

/Users/george/.npm/_npx/54858/pnpm-global/4:
+ changesets 1.0.2
command not found: changesets

**Comment by gsong** [comment]
I see, it's `pnpx changeset`. Is this process described somewhere, I looked in https://github.com/pnpm/pnpm/blob/master/CONTRIBUTING.md and didn't see it described there. But maybe I missed it there or somewhere else.

**Comment by zkochan** [comment]
I should add steps


George Song <notifications@github.com> ezt írta (időpont: 2020. aug. 16., V
16:37):

**Pull request closed without merging**
