### PR TITLE
chore: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by zkochan** [comment]
The first time it will most likely pass but after getting node_modules from the cache, it will probably fail. I tried it in the past, Travis breaks the symlinks inside node_modules when archiving.

A possible solution would be to cache the store folder but I did not see a performance improvement from that. Also, we'd have to prune the store after each installation. Otherwise a lot of garbage would be in the cache over time

**Comment by DanielRuf** [comment]
Not sure, I did not see any related issues in the past weeks. Also I have to trigger a new build after the first build has properly finished and the cache is filled with the first snapshot.

**Comment by DanielRuf** [comment]
If there are issues with Travis and the cache we can contact them (it's also a german company so there are direct contacts if needed and some of the Travis team are in the Gitter and Slack channels too).

**Comment by zkochan** [comment]
This is not valid anymore because we migrated to a monorepo.

Also, currently we dogfood the next version of pnpm, when installing dependencies on CI, so it is good that dependencies are not cached. It is an additional e2e test for pnpm

**Comment by DanielRuf** [comment]
> we dogfood the next version of pnpm

Great =)

**Pull request closed without merging**
