### PR TITLE
feat: using an internal shrinkwrap copy instead of `node_modules/.graph.yaml`

### PR DESCRIPTION
**Pull request by zkochan**
The uninstallation logic is a lot easier when comparing the internal (private) shrinkwrap file with the external one.

The internal or private (not sure what is better naming) `shrinkwrap.yaml` is inside `node_modules` and is copy of the outer one of the `shrinkwrap.yaml` file from the root of the project.

This internal `shrinkwrap.yaml` will also allow to make a lot of different checks/verification after changing git branches or doing some manual changes in the project

Ref #658

### Breaking Changes

* cannot insall a dependency w/o saving
* a `node_modules/.shrinkwrap.yaml` file is used for storing info about the dependencies, instead of a `node_modules/.graph.yaml` file

### CODE REVIEW

**Comment by iamstarkov** [comment]
> cannot insall a dependency w/o saving

nothing new, the same thing with ordinary npm

**Comment by zkochan** [comment]
Are you sure? I just tried `npm install is-negative` with `npm@3.10.9` and it did not update my package.json. Maybe you have some config changes?

**Comment by iamstarkov** [comment]
oh, misread. i initially thought you meant that i can install things, though it wont be saved in pkg

**Comment by zkochan** [comment]
Seems like this command should be separate as @vjpr suggested, or verify should have some arguments to exclude checksums verification....

On a huge project, comparing of the private/publish shrinkwrap files takes less than 2 seconds. But with verification that dependencies were not modified, it requires ~10 seconds. Too slow to include in git hooks.

**Comment by vjpr** [comment]
> On a huge project, comparing of the private/publish shrinkwrap files takes less than 2 seconds.

You mean a simple diff of `shrinkwrap.yml` and `node_modules/shrinkwrap.yaml` right?

Shouldn't this be near-instant? We could also hash dep trees to optimize if necessary.

**Comment by zkochan** [comment]
In the evening I will try to make it faster, maybe just comparing the raw files, w/o parsing them

**Comment by zkochan** [comment]
I'll merge everything but the last commit and then will create a separate PR for the new command

**Pull request merged**
