### PR TITLE
feat: enable-modules-dir=false

### PR DESCRIPTION
**Pull request by zkochan**
Continuation of #3047

Is it a good name for the option?

### CODE REVIEW

**Comment by ematipico** [comment]
If the value of this new option is a Boolean, I would suggest a different name. The current name makes me think that I should provide a path to a directory:

-  `write-modules`
- `write-modules-in-dir`

**Comment by zkochan** [comment]
What about enable-modules-dir?

Emanuele <notifications@github.com> ezt írta (időpont: 2021. jan. 3., V
10:44):

**Comment by zkochan** [comment]
Or modules-dir-enabled

Zoltan Kochan <zoltankochan@gmail.com> ezt írta (időpont: 2021. jan. 3., V
12:16):

**Comment by ematipico** [comment]
`enable-modelus-dir` is a sound variable, I like it!

**Pull request merged**
