### PR TITLE
Exclude VS Code properties from environment variables

### PR DESCRIPTION
**Pull request by d13**
See https://github.com/pnpm/pnpm/issues/8552

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/pnpm/pnpm?shareId=237f341e-7967-4fd1-af65-f2c399aedfa6).

### CODE REVIEW

**Comment by zkochan** [comment]
If I understand correctly, we automatically add all fields from `package.json` to env variables. If that is the case, we need to check what field does npm include and use the same list.

**Comment by zkochan** [comment]
I believe it happens in this function: https://github.com/pnpm/npm-lifecycle/blob/1e0f149176877f906968a01087cf63290652ccbc/index.js#L347

See all the env variables created with the `npm_package_` prefix. We should find how npm does it. Probably it has an allowlist of fields.

**Comment by d13** [comment]
@zkochan  I will dig into that, thanks!

**Comment by eamodio** [comment]
It looks like it is here: 

https://github.com/npm/cli/blob/6ca609e20b68fb2e5ef8177db116b84a339461fd/workspaces/arborist/lib/arborist/rebuild.js#L311-L320

I also verified that on my Windows box that those are the only `npn_package_` prefixed env variables I see when a script is run

**Comment by zkochan** [comment]
There is an RFC about this change in npm CLI: https://github.com/npm/rfcs/blob/5f53b903b4b92881a9b7fc73e2994c33e419975c/implemented/0021-reduce-lifecycle-script-environment.md

**Pull request closed without merging**
