### PR TITLE
feat: support package.yaml and package.json5

### LINKED ISSUE #1100: Support package.yaml
Will it be feasible to support a yaml alternative to package.json ? 

JSON is really not a good configuration format and yaml would be beneficial in many ways: 

- Supports comments

  This is the single biggest advantage. I find myself wondering so many times why a specific rc/alpha/outdated version was included in the package (instead of the latest stable), Some details about a script etc.

- Supports anchors 
    
    Remove duplication between peer deps and dev deps etc.

- Multiline strings

    Useful for npm scripts involving commands

etc.

### PR DESCRIPTION
**Pull request by zkochan**
close #1100

- [x] preserve indentation
- [x] make it work in monorepo
- [x] only write the manifest file if it has changes

### CODE REVIEW

**Comment by zkochan** [comment]
@octogonz I just noticed you in json5 repo https://github.com/json5/json5/issues/190. Probably this feature will be interesting to you

**Comment by octogonz** [comment]
Thanks! I added some thoughts to #1100

**Review by minamir85 — APPROVED** [review]

**Review by Mohstarclassnet — COMMENTED** [review]
To implement real-time data harvesting for your banking/investment platform, you need both:
	1.	A Web Scraper (Program) – To collect financial data from various sources.
	2.	An Application (Dashboard/API) – To process, store, and display the data for users.

1. Web Scraper (Python Program)

This Python script collects financial data (such as stock prices, exchange rates, and news) from web sources every minute.

Requirements

Install the necessary libraries:

pip install requests beautifulsoup4 schedule pandas

Python Code for Real-Time Data Harvesting

import requests
from bs4 import BeautifulSoup
import schedule
import time
import pandas as pd

# Function to scrape financial data
def fetch_financial_data():
    url = "https://www.example.com/finance"  # Replace with actual financial data source
    headers = {"User-Agent": "Mozilla/5.0"}
    
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        
        # Example: Extract stock prices (Modify as needed)
        stocks = soup.find_all("div", class_="stock-price")  
        data = [{"Stock": stock.text} for stock in stocks]
        
        # Save data to CSV (or database)
        df = pd.DataFrame(data)
        df.to_csv("financial_data.csv", mode='a', index=False, header=False)
        
        print("Data collected and saved.")
    else:
        print("Failed to fetch data.")

# Schedule the scraper to run every minute
schedule.every(1).minutes.do(fetch_financial_data)

print("Starting data harvesting...")
while True:
    schedule.run_pending()
    time.sleep(1)

What This Does:
	•	Scrapes financial data (e.g., stock prices).
	•	Stores it in a CSV file (can be extended to a database).
	•	Runs every minute automatically.

2. Application (Dashboard/API)

The backend application should:
	1.	Process the collected data.
	2.	Display insights to users.
	3.	Send alerts on financial trends.

Tech Stack Options:

	•	Backend: Flask/Django (Python) or Node.js
	•	Frontend: React.js/Vue.js
	•	Database: PostgreSQL/MySQL/MongoDB
	•	Hosting: AWS, Azure, or your preferred cloud service

Would you like me to generate a Flask API or a Full-Stack Web App for real-time financial data visualization?

**Comment by yousufmirpro** [comment]
Yousufmir4848@gmail.com
Yousuftanjid69@ no worries my friend is not activated but I yousufmir4848@gmail.com to the company and I will be able to pay for the next month of

**Comment by jg1366028-max** [comment]
[BALANCE_REPORT.xlsx](https://github.com/user-attachments/files/21935393/BALANCE_REPORT.xlsx)

**Review by jackpotpot342-prog — APPROVED** [review]

**Pull request merged**
