### PR TITLE
feat: time-based resolution mode

### PR DESCRIPTION
**Pull request by zkochan**
Related RFC: https://github.com/pnpm/rfcs/pull/2

TODO

- [x] add tests
- [x] prefer latest versions
- [x] add some delta to the publishedBy date
- [x] remove not needed fields from the full meta before saving it to disk
- [x] save publishedBy (it should also include the id of the last published package) in the lockfile and don't use forceResolution

### CODE REVIEW

**Comment by Jack-Works** [comment]
is it the `--before` option in npm? https://docs.npmjs.com/cli/v8/using-npm/config#before 🤔

**Comment by zkochan** [comment]
I did not know about `before`.

This works partially as before. Please review my RFC: https://github.com/pnpm/rfcs/pull/2

**Review by mcmxcdev — APPROVED** [review]
Looks really solid, couldn't spot anything!

**Comment by Jack-Works** [comment]
if we switch to this new resolution mode for an existing project, does it cause our dependency to be downgraded? 👀

**Pull request merged**
