### PR TITLE
pnpm recursive link|dislink

### PR DESCRIPTION
**Pull request by zkochan**
- [ ] warnings should be reported when running `pnpm recursive ...`

### CODE REVIEW

**Comment by vjpr** [comment]
@zkochan Is there a way to ignore packages being linked. 

I had some 3rd party packages I extracted and it tired to run the post-install scripts which are broken.

**Comment by zkochan** [comment]
there is no way, as of now.

I was thinking also about adding some mapping or caching the location of packages. On a big monorepo, the lookup of all the packages takes some time

**Comment by vjpr** [comment]
What about using a config setting with a glob, just like `lerna.json`?

**Comment by zkochan** [comment]
We should support something like that but I don't know what would be the best way to support it. A new config file?

**Comment by vjpr** [comment]
What about in the `pnpmfile.js`?

**Comment by zkochan** [comment]
sounds good to me

**Pull request merged**
