### PR TITLE
fix(deploy): ensure that the deploy target is generated in the same directory

### LINKED ISSUE #6858: pnpm deploy generate multiple deploy target directories in different directories
### Code to reproduce the issue:
As commented in https://github.com/pnpm/pnpm/issues/6697#issuecomment-1649626977,  give a workspaces with the following directory structure:

```
./
├── project-1
│   └── package.json
├── project-3
│   └── package.json
├── sub-dir
│   └── project-2
│       └── package.json
├── package.json
└── pnpm-workspace.yaml


// project-1/package.json
{
	"name": "project-1",
	"version": "1.0.0",
	"dependencies": {
		"is-positive": "1.0.0"
	}
}

// project-3/package.json
{
	"name": "project-3",
	"version": "2.0.0",
	"dependencies": {
		"is-number": "1.0.0"
	}
}

// sub-dir/project-2/package.json
{
	"name": "project-2",
	"version": "2.0.0",
	"dependencies": {
		"is-odd": "1.0.0"
	}
}

// pnpm-workspace.yaml
packages:
  - project-1
  - project-3
  - sub-dir/project-2
```

After run `pnpm  --filter project-1 deploy ./dist`, you will find that `dist` directory  occurs in the project root directory and `./sub-dir`.

### Expected behavior:

Deploy target directory(./dist) should only generated to project root directory.

### Actual behavior:
Deploy generate multiple deploy target directories in different directories

### Additional information:

 - `node -v` prints: v16.15.1
 - Windows, macOS, or Linux?: macOS

### PR DESCRIPTION
**Pull request by await-ovo**
fix #6858

### CODE REVIEW

**Review by zkochan — COMMENTED** [review]
What was the issue with dedupePeerDependents?

Is the modules directory issue covered with a test?

I am not sure why all module directories should be updated, I'll have to look into it.

**Comment by await-ovo** [comment]
> What was the issue with dedupePeerDependents?

The original issue [here](https://github.com/pnpm/pnpm/issues/6697) should be related to `pnpm --filter pattern install` not working in `dedupe-peer-dependents=true`.

> Is the modules directory issue covered with a test?

Yes,  In this [test](https://github.com/pnpm/pnpm/blob/e6b74d7bc781aa93735666638634d7e3a4048c97/releasing/plugin-commands-deploy/test/deploy.test.ts#L88), `pnpm --filter project-1 deploy ./deploy` will generate `deploy/node_modules` in the project root directory and `sub-dir` directory at the same time,  this pr fixes it ~.

> I am not sure why all module directories should be updated, I'll have to look into it.

Take `pnpm filter project-1 deploy ./deploy`as an example, the[ modulesDir set here ](https://github.com/pnpm/pnpm/blob/main/releasing/plugin-commands-deploy/src/deploy.ts#L94)is only relative to `project-1`, which is `./deploy/node_modules`. In the case of `dedupe-peer-dependents=true` by default, we will install dependencies for all projects, and eventually the dependencies of `sub-dir/project-2` will be written to `/sub-dir/deploy/node_modules` during  pnpm deploy. 

So I updated the modulesDir of all projects here to ensure that the relative path is correct.

**Comment by zkochan** [comment]
It is not a good fix. The issue is happening because deploy should run on a single project but when dedupe-peer-dependnents it true, all projects are selected:

https://github.com/pnpm/pnpm/blob/32679f0ad4762d5c429053e121d52ade85ef4142/pkg-manager/plugin-commands-installation/src/installDeps.ts#L167-L171

The easiest fix would be to always set dedupe-peer-dependnents to true, when running install during deploy.

**Review by zkochan — APPROVED** [review]

**Comment by await-ovo** [comment]
> It is not a good fix. The issue is happening because deploy should run on a single project but when dedupe-peer-dependnents it true, all projects are selected:

I just noticed that even though `dedupe-peer-dependents` is set to false,`deploy` will installs the workspace root dependencies at the same time. Inside [the repository here](https://github.com/await-ovo/pnpm-deploy-issue-reproduce),  we can see that `../../pruned/node_modules` is generated at the same time after running `pnpm --filter foo deploy ./pruned`.

It looks like we need to set the `modulesDir` for each project separately, in addition to setting `dedupe-peer-dependents` to false.

**Pull request merged**
