### PR TITLE
fix publishConfig.directory script

### PR DESCRIPTION
**Pull request by PabloSzx**
the implementation in #3490 had a mistake that the test didn't catch 😞, now I tested it locally and now it for sure works as expected

### CODE REVIEW

**Comment by PabloSzx** [comment]
@zkochan, there is something wrong going on, in the first screenshot I'm logging args[0] in the pnpm.cjs of v6.7.0

image


And in this screenshot I'm logging args[0] directly in the source code and running the tests 

image

**Comment by zkochan** [comment]
The issues are because of this section probably. I guess it should be fixed.

https://github.com/pnpm/pnpm/blob/3bd6ad8e64e7f30ef29c54fdd125293907ef067c/packages/plugin-commands-publishing/src/publish.ts#L179-L189

**Comment by PabloSzx** [comment]
> The issues are because of this section probably. I guess it should be fixed.
> 
> https://github.com/pnpm/pnpm/blob/3bd6ad8e64e7f30ef29c54fdd125293907ef067c/packages/plugin-commands-publishing/src/publish.ts#L179-L189

I don't think that is the issue, here I'm printing the original args the very beginning of the handler
image

**Comment by PabloSzx** [comment]
Mmm, I was thinking about this issue wrong, the problem here is that the recursivePublish specified the directory in the script itself 
image

**Comment by zkochan** [comment]
I see, in that case I recommend to change how recursive publish passes the directory. Instead of passing it through argv.original, pass it through the dir option.

**Comment by zkochan** [comment]
I mean

```
        const publishResult = await publish({
          ...opts,
          dir: pkg.dir,
          argv: {
            original: [
              'publish',
              '--tag',
              tag,
              '--registry',
              pickRegistryForPackage(opts.registries, pkg.manifest.name!),
              ...appendedArgs,
            ],
          },
          gitChecks: false,
          recursive: false,
        }, [])

```

**Review by zkochan — APPROVED** [review]

**Pull request merged**
