### PR TITLE
feat: enable-pre-post-scripts

### PR DESCRIPTION
**Pull request by zkochan**
ref #2891

### CODE REVIEW

**Comment by jmcdo29** [comment]
This is great! Thank you for adding a config back in for this!

**Comment by shellscape** [comment]
Really, really appreciate this.

**Review by ExE-Boss — APPROVED** [review]

**Comment by zkochan** [comment]
:ship: 6.1.0

**Comment by fedor-pavlov** [comment]
Is it a good time to think about a meta-scripts?
like:
```
{
  "scripts": {
     "build": [
          "tsc ...",
          "echo do step_1",
          "echo do step_2",
          "zip -r index.zip index.js*"
     ]
  }
}
```

I mean people need multi-line scripts. It's obvious.
And they don't want to deal with all of those ` ... && ...`, because it works differently on different platforms and generate annoying errors. Moreover, the `&&` logic is not equivalent to a series of script lines.

Let's introduces arrays to `"script"` object?
It gives people multiline and solves all those ugly `pre-/post- scripts` issues as well as `enable-pre-post-scripts` "crutches and patches"

**Comment by pho3nixf1re** [comment]
At that point you should probably adopt a build system or something much better suited to the task. The npm scripts are really just shortcuts to execute commands in the context of the local node_modules and _not_ a full build step management system.

**Comment by shellscape** [comment]
while I agree with @pho3nixf1re that there are better tools for complex builds, I disagree that npm scripts are limited in the way he suggests - there is no official guidance that warns users off from using it as a build system, and in the days between grunt/gulp and more mature tools, it often was and very successfully so.

**Comment by pho3nixf1re** [comment]
Not to derail the review topic here but I actually agree with you here. What I meant is that pnpm shouldn't add-on to the scripts complexity to try and emulate build steps and dependencies. That is where Gulp, make, and other tools step in. But you can absolutely execute those using the scripts in package.json and it is even recommended since it already has the context of `node_modules/.bin`

**Comment by zkochan** [comment]
Sorry but the conversation was not relevant to the PR.

**Pull request merged**
