### PR TITLE
feat(server): choosing the communication protocol

### LINKED ISSUE #987: It should be possible to specify how to connect to the pnpm server
Right now the connection details are decided by the OS on which the server is running. Is it possible to add a couple options to specify them manually?

### PR DESCRIPTION
**Pull request by zkochan**
close #987

### CODE REVIEW

**Comment by zkochan** [comment]
@etamponi, please review

**Comment by etamponi** [comment]
I think this is good enough for my specific use case; what I would have done though, to make it even more configurable, is providing a `--port` option instead, with the following possible values:

- `auto`: same as `--protocol auto`
- `unix`: same as `--protocol ipc`
- `N`: same as `--protocol tcp`, but it also allows you to pick any port you want. This way you're not constrained to use port 5813 (which is also good for security), and you can even have multiple servers running.

In general being able to specify the listening port would be good.

But all these things aren't fundamental for me, you can also ship it as it is 👍 

Thanks!

**Comment by zkochan** [comment]
I think it is a bit confusing to use `--port` for setting the protocol. However, I agree that it is a good feature to be able to set the protocol.

How about this:

* I leave `--protocol` as it is now
* if `--port` is passed but no `--protocol` then `tcp` is used with the specified protocol.
* setting protocol to unix and specifying the port throws an error

**Comment by etamponi** [comment]
I like your idea 👍

**Comment by zkochan** [comment]
Published in `1.27.0`

**Pull request merged**
