### PR TITLE
feat: use file: instead of link: for compatibility with npm

### LINKED ISSUE #1332: Local dependency install incompatible with npm
### Code to reproduce the issue:
Per #1061, installing local dependencies with pnpm, adds `link:`s to `package.json`, making the package uninstallable on npm (tested with 5.6.0, 6.4.0) with the error
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:X                                               
```

Maybe change to install local dependencies by `file:`s instead? I opened a [corresponding issue](https://npm.community/t/is-link-or-file-supported/1577) on the npm issue tracker.

### PR DESCRIPTION
**Pull request by zkochan**
BREAKING CHANGE: dir deps are saved via file:

close #1332

### CODE REVIEW

**Comment by ExE-Boss** [comment]
Note that this will be incompatible with **Yarn**, as **Yarn** uses `link:` for this as well.

**Comment by zkochan** [comment]
doesn't Yarn support both?

**Comment by ExE-Boss** [comment]
Yes, but only `link:` creates symbolic links.

**Comment by zkochan** [comment]
In npm `file:` creates a symbolic link

**Pull request closed without merging**
