### PR TITLE
fix: ~7% smaller bundle size by not packing unneeded yarnpkg/nm subdeps

### PR DESCRIPTION
**Pull request by ChALkeR**
Replace `@yarnpkg/nm` import with direct `@yarnpkg/nm/hoist` import and remove a large unused code subtree

Refs: https://github.com/yarnpkg/berry/pull/6611

Two commits so that the first one can be tested individually if needed -- it produces no changes in the `dist`

Before: `9563553` bytes, after: `8920653` bytes for `dist/pnpm.cjs`

More reduction is possible (to ~`7551098` bytes, ~21% total) by fixing other usused yarnpkg imports, but let's start with this one

### CODE REVIEW

**Comment by ChALkeR** [comment]
Should this be backported to v9?

**Comment by zkochan** [comment]
Is it safe?

**Comment by ChALkeR** [comment]
@zkochan
1. tsconfig changes -- completely safe, it had zero effect on the generated bundle
2. Import change / code removal -- completely safe, it was unused
3. `@yarnpkg/nm` version bump 4.0.2 -> 4.0.5 -- unsure. That's a semver-patch release though?

    These two prs did touched the code used here:
      * https://github.com/yarnpkg/berry/pull/6495
      * https://github.com/yarnpkg/berry/pull/6517

**Comment by ChALkeR** [comment]
Follow-up in https://github.com/pnpm/pnpm/pull/8810

**Pull request merged**
