### PR TITLE
docs(README): add node compatibility badge

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Comment by zkochan** [comment]
I don't think it is needed because pnpm actually works with any node.js on the system if it is installed via the standalone script, which installs pnpm with node.js bundled with it.

**Comment by btea** [comment]
If so, the engines field in [package.json](https://github.com/pnpm/pnpm/blob/main/pnpm/package.json) can be removed. 🤔

**Comment by zkochan** [comment]
No, it cannot be removed because the plain js version still requires node.js 16. And even when it is bundled with pkg, it is bundled with a supported node.js version.

**Comment by btea** [comment]
Ok, thanks for your reply, let's close it,

**Pull request closed without merging**
