### PR TITLE
support for `type` and `imports` in publishConfig

### PR DESCRIPTION
**Pull request by ScottAwesome**
This PR is for allowing `type`  and imports to be controlled in the `package.json` when used with `publishConfig`. This is so that during development, in particular with a monorepo (though I imagine others may find this useful too), it can be challenging when on a project to be able to seamlessly work across dependencies, [when `type` is is defined](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_type) because it will look for either a `.mjs` or .`cjs` extension, however at build time its fairly easy to export the correct `.cjs` and `.mjs` extensions for a project (library or otherwise), which when combined with exports can [get around some issues with the dual package hazard problem](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_dual_package_hazard)

The `imports` field as well should be supported, to maintain fidelity with the fact `exports` is also supported, [per the spec](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_imports).

This appears to be a simple two line change, but I may not understand very well the codebase here, please let me know if there is something I missed!

### CODE REVIEW

**Comment by ScottAwesome** [comment]
I'd be willing to open up the conversation to say that maybe it should just make arbitrary overrides, I don't know how everyone feels about that though.

**Comment by zkochan** [comment]
I don't know, overriding anything sounds good, I guess. Do you know how Yarn works with this field?

cc @pnpm/collaborators

**Comment by ExE-Boss** [comment]
> [when `type` is is defined](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_type) because it will look for either a `.mjs` or .`cjs` extension

That’s incorrect, as the **CommonJS** resolver only makes the `.js` extension optional. The `.cjs` and `.mjs` extensions must always be specified in both **ESM** and **CommonJS**.

**Comment by ScottAwesome** [comment]
> > [when `type` is is defined](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_type) because it will look for either a `.mjs` or .`cjs` extension
> 
> That’s incorrect, as the **CommonJS** resolver only makes the `.js` extension optional. The `.cjs` and `.mjs` extensions must always be specified in both **ESM** and **CommonJS**.
> 
>     * I’m against adding `type` to `publishConfig`.
> 
>     * I’m neutral on adding `imports` to `publishConfig`.



> > [when `type` is is defined](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_type) because it will look for either a `.mjs` or .`cjs` extension
> 
> That’s incorrect, as the **CommonJS** resolver only makes the `.js` extension optional. The `.cjs` and `.mjs` extensions must always be specified in both **ESM** and **CommonJS**.
> 
>     * I’m against adding `type` to `publishConfig`.
> 
>     * I’m neutral on adding `imports` to `publishConfig`.

Ah yes, that is true, I think the nodejs docs around this have been updated to better reflect this too.

Why against adding type though? I'm not sure I see any real issue with this, as its not pnpm's responsiblity to make sure we use the field right (and its optional anyway). Myself I feel this would make it easier to work inside of a monorepo in particular

**Comment by zkochan** [comment]
Please create a changeset by running `pnpm -w changeset`

**Comment by ScottAwesome** [comment]
> Please create a changeset by running `pnpm -w changeset`

done 😄 👍

**Comment by ExE-Boss** [comment]
`imports` doesn’t really affect consumption though.

---

And `type` only affects the parse target of `.js` files, and it’s impractical to make a `.js` file that can be parsed as both a **CommonJS** and **ESM** file.

Because of this, it doesn’t make sense to support `type` in `publishConfig`.

**Comment by ScottAwesome** [comment]
> `imports` doesn’t really affect consumption though.
> 
> And `type` only affects the parse target of `.js` files, and it’s impractical to make a `.js` file that can be parsed as both a **CommonJS** and **ESM** file.
> 
> Because of this, it doesn’t make sense to support `type` in `publishConfig`.

It does because it’s whole purpose is to define effectively an alias for when something is imported based on a condition.

I disagree that type doesn’t affect consumption either, just see the recent exports map fiasco Babel just dealt with

**Comment by zkochan** [comment]
This is 1:1 and I am neutral. Let's wait for other opinions.

**Comment by ScottAwesome** [comment]
@zkochan I don't think there's must resistance to this, judging from the time of open commentary we've left thus far.

**Review by zkochan — APPROVED** [review]

**Pull request merged**
