### PR TITLE
fix(side-effect): cache when not sharing lockfile

### PR DESCRIPTION
**Pull request by KSXGitHub**
fixes https://github.com/pnpm/pnpm/issues/6890

### CODE REVIEW

**Comment by zkochan** [comment]
Related PR: https://github.com/pnpm/pnpm/pull/6796

**Comment by zkochan** [comment]
How are these changes related to https://github.com/pnpm/pnpm/issues/6890 if the issue is about `pnpm install` but these changes affect only the `pnpm rebuild` command?

**Comment by KSXGitHub** [comment]
> How are these changes related to #6890 if the issue is about `pnpm install` but these changes affect only the `pnpm rebuild` command?

I found out after experiment with `console.log`. I only used `install`, not `rebuild`.

Maybe the true cause of the bug was pnpm incorrectly invoke rebuild?

**Comment by zkochan** [comment]
The tests are failing.

**Comment by KSXGitHub** [comment]
> The tests are failing.

Re-run `pnpm recursive rebuild with hoisted node linker` locally and it passes. Not sure why it fails or even what fails.

**Comment by KSXGitHub** [comment]
When lockfile is not shared, `opts.lockfileDir` is `undefined`, causing early `return true` not to be executed, allowing it to eventually reach `rebuild.handler`.

**Comment by KSXGitHub** [comment]
I suspect the cause of the failing tests was some sort of race condition. When I run only one test, regardless of which one, it always succeed. It only fails when I run all of them.

**Comment by KSXGitHub** [comment]
@zkochan Fixing this could be as simple as removing the aforementioned 2 lines, but I'm not sure how exactly pnpm should behave.

**Comment by zkochan** [comment]
The related issue is about the `pnpm install` command, so I guess a safe fix would be to just set `skipIfHasSideEffectsCache` to `true`, when running rebuild from `plugin-commands-installation`.

So add the option here:

https://github.com/pnpm/pnpm/blob/6abd24ef0514e93b714c3d138efc99c8e64159db/pkg-manager/plugin-commands-installation/src/installDeps.ts#L318-L331

and here:

https://github.com/pnpm/pnpm/blob/6abd24ef0514e93b714c3d138efc99c8e64159db/pkg-manager/plugin-commands-installation/src/recursive.ts#L413-L416

This is probably the right fix as the current fix would change how the `pnpm rebuild` command works, which is probably not good and why the test started to fail.

**Pull request closed without merging**
