### PR TITLE
fix: don't extend NODE_PATH in command shims

### LINKED ISSUE #5285: The extend-node-path option does not appear to behave like false, on pnpm7
I went through node-path issues at pnpm6. 
It was solved by giving the extend-node-path option to false.
During the pnpm7 migration, we encountered the same issue.

### pnpm version:
7.9.4

### Code to reproduce the issue:
When I exec `node_modules/.bin/jest`, then NODE_PATH is exported

### Expected behavior:
```diff
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

- if [ -z "$NODE_PATH" ]; then
-   export NODE_PATH="/Users/kiwi.jang/Desktop/toss/web-automation-batch/node_modules/.pnpm/node_modules"
- else
-   export NODE_PATH="$NODE_PATH:/Users/kiwi.jang/Desktop/toss/web-automation-batch/node_modules/.pnpm/node_modules"
- fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/jest@29.0.0_@types+node@16.11.45/node_modules/jest/bin/jest.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/jest@29.0.0_@types+node@16.11.45/node_modules/jest/bin/jest.js" "$@"
fi
```

### Actual behavior:
```diff
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

+ if [ -z "$NODE_PATH" ]; then
+   export NODE_PATH="/Users/kiwi.jang/Desktop/toss/web-automation-batch/node_modules/.pnpm/node_modules"
+ else
+   export NODE_PATH="$NODE_PATH:/Users/kiwi.jang/Desktop/toss/web-automation-batch/node_modules/.pnpm/node_modules"
+ fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/jest@29.0.0_@types+node@16.11.45/node_modules/jest/bin/jest.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/jest@29.0.0_@types+node@16.11.45/node_modules/jest/bin/jest.js" "$@"
fi
```

### Additional information:
 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: macOS

related pr: https://github.com/pnpm/pnpm/pull/4253

### PR DESCRIPTION
**Pull request by zkochan**
close #5285

### CODE REVIEW

**Comment by WhiteKiwi** [comment]
👍 oh Thank you for the quick commit

**Comment by zkochan** [comment]
Actually, NODE_PATH was added back to fix `next` https://github.com/pnpm/pnpm/pull/4513, so I can't merge this if it breaks next

**Comment by WhiteKiwi** [comment]
May I ask what the next issue is?
And can I reproduce it? 🙇

**Comment by zkochan** [comment]
I don't remember. I'll try to add an e2e test for it.

**Comment by zkochan** [comment]
I couldn't reproduce the issue with `next dev`. And I also can't think of an issue with removing this. I hope I am not making a mistake but it looks like it is ok to turn it off in a non-major release.

**Pull request merged**
