### PR TITLE
ci: set workflow dispatch inputs to Winget Releaser

### PR DESCRIPTION
**Pull request by sitiom**
You will have to put the inputs to Winget Releaser manually if you are going to do a workflow dispatch. Please try triggering the workflow again after merging.

### CODE REVIEW

**Comment by sitiom** [comment]
Also, `post-to-reddit` job doesn't seem to have the release environment?

**Review by zkochan — APPROVED** [review]

**Comment by sitiom** [comment]
@zkochan https://github.com/pnpm/pnpm/actions/runs/4060217723/jobs/6989090485

```
  HTTP 401: Personal access tokens with fine grained access do not support the GraphQL API (https://api.github.com/graphql)
```

I'm guessing you would have to set a classic token.

**Comment by sitiom** [comment]
- @zkochan https://github.com/pnpm/pnpm/actions/runs/4060315926/jobs/6989335300 Error is due to https://github.com/vedantmgoyal2009/winget-releaser/issues/86. As a workaround, try rerunning the failed workflow until it works.

**Comment by zkochan** [comment]
I did 4 attempts. It didn't work.

**Comment by sitiom** [comment]
Perhaps try again later. The first attempt worked, though; you just had a fine-grained token.

**Comment by zkochan** [comment]
Wait, I see a PR, so I guess it worked: https://github.com/microsoft/winget-pkgs/pull/95215

**Comment by sitiom** [comment]
> Wait, I see a PR, so I guess it worked: [microsoft/winget-pkgs#95215](https://github.com/microsoft/winget-pkgs/pull/95215)

That's my PR that I manually made using the previous run's generated branch 😅

**Comment by zkochan** [comment]
oh, OK 

I was surprised that it is using your account

**Comment by sitiom** [comment]
- Now it works: https://github.com/microsoft/winget-pkgs/pull/95888

**Comment by zkochan** [comment]
yes, after several restarts it worked.

**Pull request merged**
