### PR TITLE
fix(dlx): race condition

### PR DESCRIPTION
**Pull request by KSXGitHub**

### CODE REVIEW

**Comment by zkochan** [comment]
Is this still needed after https://github.com/pnpm/symlink-dir/pull/59?

**Comment by KSXGitHub** [comment]
> Is this still needed after [pnpm/symlink-dir#59](https://github.com/pnpm/symlink-dir/pull/59)?

`EEXIST` is still possible. I have force pushed another change.

**Review by zkochan — APPROVED** [review]

**Comment by literalpie** [comment]
Will this be released in a 9.x release or only 10.x? I suspect this might fix #7713

**Comment by literalpie** [comment]
This has been released in 9.13.2, but I'm still seeing #7713

**Pull request merged**
