### PR TITLE
fix(prune): should work in a workspace

### LINKED ISSUE #4647: [pnpm v7] pnpm prune: ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE
### Code to reproduce the issue:

> `package.json`

```json
{
  "packageManager": "pnpm@7.0.0",
  "devDependencies": {
    "@workspace/cli": "workspace:*"
  }
}
```

> `pnpm-workspace.yaml`

```yaml
packages:
  - 'packages/*'
```

> `packages/cli/package.json`

```json
{
    "name": "@workspace/cli"
}
```

Windows 11, Node 17.9

```shell
$ pnpm install

Scope: all 2 workspace projects
Already up-to-date

devDependencies:
+ @workspace/cli <- packages\cli

$ pnpm prune

 ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for @workspace/cli@* inside the workspace
```

### PR DESCRIPTION
**Pull request by zkochan**
close #4647

### CODE REVIEW

**Comment by humphd** [comment]
Based on this fix, is the [warning in the docs](https://pnpm.io/cli/prune) still correct, or outdated?

> WARNING
> The prune command does not support recursive execution on a monorepo currently. To only install production-dependencies in a monorepo node_modules folders can be deleted and then re-installed with pnpm install --prod.

**Comment by Jintus** [comment]
up

**Comment by jainmohit2001** [comment]
@zkochan

**Comment by switz** [comment]
> Based on this fix, is the [warning in the docs](https://pnpm.io/cli/prune) still correct, or outdated?
> 
> > WARNING
> > The prune command does not support recursive execution on a monorepo currently. To only install production-dependencies in a monorepo node_modules folders can be deleted and then re-installed with pnpm install --prod.

Any word on this? Doesn't seem to work (or I'm doing something wrong).

**Pull request merged**
