### PR TITLE
ci: add Winget Releaser workflow

### PR DESCRIPTION
**Pull request by sitiom**
This action automatically generates manifests for the Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)).

pnpm is in Winget (https://github.com/pnpm/pnpm/issues/3112#issuecomment-1285403232) but is outdated because updates are being manually pushed to winget-pkgs for each new version. Winget Releaser should solve this problem.

**Before merging this:**
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @pnpm. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

The documentation and source code of the action is available [here](https://github.com/vedantmgoyal2009/winget-releaser/).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

### CODE REVIEW

**Review by zkochan — APPROVED** [review]

**Comment by sitiom** [comment]
@zkochan Did you forget to add the `WINGET_TOKEN` secret? https://github.com/pnpm/pnpm/actions/runs/4034965958/jobs/6936614650

**Comment by zkochan** [comment]
No

image

**Comment by zkochan** [comment]
But this new job doesn't have the release environment, so that is the issue.

**Comment by sitiom** [comment]
Did you add it after the first run? Reruns do not get updated secrets.

**Comment by zkochan** [comment]
As I said above, the issue is that the new job doesn't have the environments field, like the build job: 

https://github.com/pnpm/pnpm/blob/5716822ddfa4fd593314aff7c1e349838474b283/.github/workflows/release.yml#L16

**Comment by sitiom** [comment]
Ah, I see now.

**Pull request merged**
