### PR TITLE
perf: request corgi (stripped) metadata from npm registry

### LINKED ISSUE #1176: Requesting corgi (non-full-metadata) when resolving dependencies
To do #1109 we had to load the full metadata instead of the stripped (corgi as npm calls it) one. However, the full metadata is bigger, so it causes performance issues to load it.

The alternative (and recommended) solution is to request the corgi metadata and then read the `package.json` from the unpacked package directory.

Cons:
* this will make it impossible to generate a `shrinkwrap.yaml` file w/o downloading the package tarball. Currently, when installation is run with the `--shrinkwrap-only` flag, tarballs are not downloaded.

### PR DESCRIPTION
**Pull request by zkochan**
close #1176

### CODE REVIEW

**Comment by zkochan** [comment]
@pgonzal this change makes pnpm use corgi

@rarkins unfortunately after this change pnpm will download package tarballs even when `--shrinkwrap-only` is used. According to the npm team, the only reliable way to tell whether a package has to be built is to check the real `package.json` from the tarball.

**Comment by rarkins** [comment]
@zkochan that's certainly a pity! 

What is the difference that enables `npm` itself to generate lock files without downloading tarballs, and can you update to do the same technique soon?

I will monitor the performance impact in the app - disk churn when using EBS on AWS can really drag performance. I assume that due to `pnpm`'s design, that if I can persist the `pnpm` cache then that would alleviate most of the network burden, transferring it instead to be a disk burden? I did that previous with `yarn` but it was ultimately too much disk I/O that it slowed things down almost as much.

**Comment by pgonzal** [comment]
> unfortunately after this change pnpm will download package tarballs even when --shrinkwrap-only is used. According to the npm team, the only reliable way to tell whether a package has to be built is to check the real package.json from the tarball

A few questions:

When you say "download the tarball" do you mean it would get downloaded even if it's already present in the PNPM store?

Is the NPM team saying that the huge dump of package.json returned from their REST endpoint may NOT accurately represent the actual contents of the package.json file? How would that happen?

I understood that `--shrinkwrap-only` is intended to be a fast way to update **shrinkwrap.yaml**, in cases where you don't care about the node_modules folder (e.g. because you're going to push to a PR branch without building locally).  Is that true?  Or was this feature intended to be usable without any network connection at all?

To handle @rarkins 's issue,  couldn't you simply omit the corgi header if the `--shrinkwrap-only` option was specified?

**Comment by pgonzal** [comment]
> I will monitor the performance impact in the app - disk churn when using EBS on AWS can really drag performance. 

@rarkins We found that in many cases, the tarball is actually smaller than the non-corgi protocol response.  This is because it always includes a full copy of package.json for every single version of the package since its initial release.  Might be useful to compare install times for the two approaches. The new version might actually be faster. :-)

**Comment by zkochan** [comment]
> When you say "download the tarball" do you mean it would get downloaded even if it's already present in the PNPM store?

No, it would not be re-downloaded in that case

> Is the NPM team saying that the huge dump of package.json returned from their REST endpoint may NOT accurately represent the actual contents of the package.json file? How would that happen?

Correct, they say there are packages that submit one particular `package.json` to the registry and pack another version into the tarball. I don't know how they do it.

> I understood that --shrinkwrap-only is intended to be a fast way to update shrinkwrap.yaml, in cases where you don't care about the node_modules folder (e.g. because you're going to push to a PR branch without building locally). Is that true?

Correct. That is one of the usecase. @rarkins uses it in renovateapp, which is like greenkeeper but better.

> Or was this feature intended to be usable without any network connection at all?

no

**Comment by zkochan** [comment]
> @rarkins We found that in many cases, the tarball is actually smaller than the non-corgi protocol response. This is because it always includes a full copy of package.json for every single version of the package since its initial release. Might be useful to compare install times for the two approaches. The new version might actually be faster. :-)

This might be true but maybe you'll have to prune the store from time to time, with the `pnpm store prune` command, to remove the old tarballs. Maybe we can fine-tune that command for renovate's needs.

**Comment by pgonzal** [comment]
> Correct, they say there are packages that submit one particular package.json to the registry and pack another version into the tarball. I don't know how they do it.

😵 Haha I guess I'm not surprised by that.

Anyway thanks @zkochan for doing this work!  I imagine it will make the normal install faster.

**Comment by rarkins** [comment]
@pgonzal @zkochan thanks for the feedback. I'll probably leave it for a while unless the disk/cache use becomes unbearable

**Comment by zkochan** [comment]
> I imagine it will make the normal install faster.

Yes, it will

> I'll probably leave it for a while unless the disk/cache use becomes unbearable

@rarkins I will ping you when we will implement a hook for filtering out the files that are unpacked: #804
It will be possible to tell pnpm to unpack just the `package.json`, the `binding.gyp` and the `.hooks` folder. Only those files are needed to detect if the package needs to be built

**Comment by nickpape-msft** [comment]
With this change, is there actually any speed improvement while using `--shrinkwrap-only`?

**Comment by zkochan** [comment]
@nickpape-msft yes, it is still faster than w/o `--shrinkwrap-only`. Packages are not hardlinked into the project's node_modules. No node_modules is created at all.

Using non-corgi won't help because I've been informed by a member of the npm team that the metafile in the tarball may differ from the metafile that is returned by the registry separately

**Comment by nickpape-msft** [comment]
> yes, it is still faster than w/o --shrinkwrap-only. Packages are not hardlinked into the project's node_modules. No node_modules is created at all.

Right, but this isn't really the expensive part of the operation. From what I can tell pnpm still downloads the tarballs, stores on disk, unzips, etc. If you have an empty cache this takes almost as long as when not using the flag. In the case where you have a perfectly good cache, it still takes almost nearly as long. If it really isn't significantly faster, why have the flag around at all? It will just be bait for more GitHub issues when it doesn't really do what people are thinking (e.g. have a significant speed improvement). Is there anything creative we can do to make the flag work the way it did before, where it WAS significantly faster?

**Pull request merged**
