### PR TITLE
chore(typescript): use project references

### LINKED ISSUE #2410: Use project references
Use [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) for more efficient typescript compilations.

### PR DESCRIPTION
**Pull request by zkochan**
close #2410

### CODE REVIEW

**Comment by zkochan** [comment]
Surprisingly, this is 40 seconds slower than running `pnpm run -r tsc`. Though it provides better experience during local development.

**Comment by StarpTech** [comment]
Hi @zkochan, do you still manage the project-references manually?

**Comment by zkochan** [comment]
No. I created a tool that automates them.
https://github.com/pnpm/meta-updater

Dustin Deus <notifications@github.com> ezt írta (időpont: 2021. febr. 11.,
Cs 10:51):

**Comment by StarpTech** [comment]
Nice, thank you!

**Pull request merged**
