### PR TITLE
fix: unpacking tarballs that appear to be not USTAR or GNU TAR

### LINKED ISSUE #7120: ERR_PNPM_TARBALL_EXTRACT occurs on install tgz files
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

7.33.6

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

pc: MacBook Prop 14 Ventura 13.5.2
node: v14.18.0

installing fails with error `(ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.`. 

### Describe the Bug

pc: MacBook Prop 14 Ventura 13.5.2
node: v14.18.0

installing fails with error `(ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.`. 

I'm getting struggle on ERR_PNPM_TARBALL_EXTRACT error occured 

>GET https://custom.registry.net/artifactory/api/npm/npm-virtual/handlebars/-/handlebars-4.7.8.tgz error (ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_TARBALL_EXTRACT  Failed to unpack the tarball from "https://custom.registry.net/artifactory/api/npm/npm-virtual/coa/-/coa-1.0.4.tgz": incorrect data check

### Expected Behavior

tgz file should be downloaded. 
downloading via manually entering url is works. 

### Which Node.js version are you using?

v14.18.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by zkochan**
close #7120

### CODE REVIEW

**Review by gluxon — APPROVED** [review]
nitpick: It might be worth storing `.tgz` fixtures in Git LFS. Committing the file directly causes the file to be kept around in `.git`, even if we delete it from the `main` branch in the future.

Screenshot 2024-02-20 at 12 53 27 AM

**Comment by zkochan** [comment]
@gluxon added to git lfs

**Comment by gluxon** [comment]
Thanks!

**Comment by gluxon** [comment]
Womp, thanks for giving it a shot. If we end up checking in `.tgz` files and changing them often, it might be worth trying again. On the other hand, if it's unlikely we'd remove a `.tgz` file from the repo in the future, it might not be worth the complexity of Git LFS.

**Pull request merged**
