### PR TITLE
fix!: the test command should pass all args to the underlying script

### PR DESCRIPTION
**Pull request by zkochan**

### CODE REVIEW

**Comment by zkochan** [comment]
This change might not be needed as there was https://github.com/pnpm/pnpm/pull/8491 already merged to v10 branch.

**Comment by PoomSmart** [comment]
@zkochan v10 isn't out and it looks like it will take a while. Can we have this fix for v9 as well?

**Comment by zkochan** [comment]
v10 is out. It is in beta. You can install it.

**Comment by PoomSmart** [comment]
Probably I phrased it wrong. v10 isn't out as a stable release. We don'r really want to use an alpha version on the main branch of our internal large project.

I read in Twitter that v9 active development is over, so we won't see the fix to be in v9 anymore? @zkochan

**Pull request merged**
