### PR TITLE
chore(github): add stale bot app

### PR DESCRIPTION
**Pull request by BlackHole1**
bot app: https://github.com/apps/stale

### CODE REVIEW

**Comment by BlackHole1** [comment]
request approve

image

**Comment by zkochan** [comment]
I am against this feature. I don't see much value in it. These bots are annoying me in other repositories.

**Comment by BlackHole1** [comment]
The advantage of this is that it automatically closes issues that have not had any activity for a long time.

Just like these [2017](https://github.com/pnpm/pnpm/issues?page=28&q=is%3Aissue+is%3Aopen) issues

Perhaps we could adjust the time a little longer? Like a year?

**Comment by zkochan** [comment]
We will still have lots of open issues. But we will have to deal with additional spamming by the bot. The reason I don't answer an issue is because I don't have time, because there are too many new issues a day. Adding even more notifications from the stale bot will not help. And automatically closing an issue just because it is old is "unfriendly". Sometimes users create a GitHub account just to file an issue.

**Comment by BlackHole1** [comment]
Okey. According to what you just said, adding a stale bot is probably not a good decision

**Comment by zkochan** [comment]
I am OK to revise this if more people will answer to issues.

**Pull request closed without merging**
