### PR TITLE
perf: don't random ID to temp file names

### PR DESCRIPTION
**Pull request by zkochan**
Related changes: https://github.com/zkochan/packages/commit/f730084cd3d487cbcbe29dd1a05c41b8bc435356

This is one of the improvements suggested by @dmichon-msft in [this comment](https://github.com/orgs/pnpm/discussions/6376#discussioncomment-6420573)

### CODE REVIEW

**Review by dmichon-msft — APPROVED** [review]
Had to go look into the other package to understand the actual change. Might be useful to include in the PR description or changelog that it now uses the PID as the unique suffix for temp files.

What setup do you usually use for perf testing changes?

**Comment by zkochan** [comment]
I use this package for performance testing: https://github.com/pnpm/pnpm.io/tree/main/benchmarks

**Comment by zkochan** [comment]
While updating [pnpm in bit](https://github.com/teambit/bit/pull/7656), a test failed:

```
     Error: Command failed: bit link  --rewire
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
ENOENT: no such file or directory, stat '/home/circleci/.local/share/pnpm/store/v3/files/0e/881c510be971ed3ac667f69eb22ccf57c377f2e6c4ffeae310e7332ba0609bf716e5f33bc3e05f7d8e0d0572ffbd9f9d12815865eb3c6f077b789701be5a71-exec_tmp_1869'
```

I am not currently sure how these changes could cause the issue. Might be unrelated but I don't remember seeing such error in the past.

**Comment by zkochan** [comment]
Looks like it is happening because the [locker](https://github.com/pnpm/pnpm/blob/c570abb192daf3bbefe26abf3a1674059419e81a/store/cafs/src/index.ts#L38) is created multiple times. I don't think it affects pnpm CLI, just bit CLI.

**Pull request merged**
