### PR TITLE
feat: add support for version ranges in github resolver

### PR DESCRIPTION
**Pull request by andreypopp**
**Do not merged:** Discuss

This allows to depend on version ranges from github repos, for example:

    rstacruz/pnpm#>=1.0.0

This makes pnpm capable to install versioned packages from github. The first
step to liberate from npm registry!

First we try to treat github ref as version range if it is validated as such.
Then we get a list of all tags in the repo and try tp match all of them (which
are valid semver versions) against the range.

Otherwise we just fallback to the prev behaviour and treat ref as ref in github
repo — either commit, branch or tag.

Note that we need to add the same code to git resolver, probably using `git
ls-remote` command to get a list of tags for a repo.

### CODE REVIEW

**Comment by zkochan** [comment]
This looks very interesting!

I am now uniting github resolve and git resolve to solve #536, so you'll have to apply your changes there. I'll push the changes in a moment

**Comment by andreypopp** [comment]
To be honest, I don't know if I want this to be in pnpm "core" — that's a deviation from npm and while it is useful it is an additional code to maintain. What if we design an API for plugging in resolvers and then publish this as a pnpm "plugin"?

**Comment by zkochan** [comment]
yep, I agree, lets discuss this in the issue that I created #559

**Comment by andreypopp** [comment]
Closing this. Will open a new one against recent codebase when we finish #559 discussion.

**Comment by zkochan** [comment]
Git resolver moved to separate package.

This change should be done there.

https://github.com/pnpm/git-resolver

**Comment by zkochan** [comment]
:ship: `1.36.0`

**Pull request closed without merging**
