### PR TITLE
perf: faster integrity verification of the store

### PR DESCRIPTION
**Pull request by zkochan**
If a file in the store was never modified, we are not checking its
integrity.

TODO:
- [x] correctly set birthtime for a file that already existed in the store. (maybe rename the field to checkedAt)
- [x] add changeset files and more comments

### CODE REVIEW

**Comment by zkochan** [comment]
This is insane, I cannot believe I never thought about this. This makes installation up to 33% faster, when the store is hot.

**Review by juanpicado — APPROVED** [review]

**Review by aparajita — APPROVED** [review]

**Comment by zkochan** [comment]
Not all filesystems support birthtime, so I will save the birthtimes of files in the package index file.

**Review by aparajita — APPROVED** [review]

**Review by aparajita — APPROVED** [review]

**Comment by zkochan** [comment]
This performance optimization will work only for packages that were added to the store with pnpm v5.7 or newer.
I am not adding logic for updating old packages in the store.

**Review by aparajita — APPROVED** [review]

**Review by juanpicado — APPROVED** [review]
double checked LGTM

**Comment by zkochan** [comment]
Thanks for looking. I will only add a few more tests before merging.

**Pull request merged**
