### PR TITLE
feat: embed-readme option

### PR DESCRIPTION
**Pull request by dangreen**
https://github.com/pnpm/pnpm/issues/4091#issuecomment-1011437102

### CODE REVIEW

**Comment by zkochan** [comment]
Thanks for making the PR.

Let's add the new setting to `@pnpm/confg` and maybe make it true by default? We can make it `false` in [v7](https://github.com/pnpm/pnpm/discussions/3536)

In any case, I don't think people will use it as a CLI option, they will just set it in a `.npmrc` file.

**Comment by dangreen** [comment]
@zkochan 

> Let's add the new setting to @pnpm/confg

Into `Config` interface, or where?

**Comment by zkochan** [comment]
in these places also

https://github.com/pnpm/pnpm/blob/1d013d7e04282dda601d423e3312fd5816ddc393/packages/config/src/index.ts#L40

https://github.com/pnpm/pnpm/blob/1d013d7e04282dda601d423e3312fd5816ddc393/packages/config/src/index.ts#L175

**Comment by dangreen** [comment]
@zkochan 

> maybe make it true by default? We can make it false in v7

It absolutely should be `false` by default. For now, made it `true`

**Comment by zkochan** [comment]
One last thing.

Run `pnpm changeset` in the root of the repository and describe your changes. The resulting files should be committed as they will be used during release.

**Comment by dangreen** [comment]
@zkochan Will nice if some words about changeset were in the contribution guide.

**Review by zkochan — APPROVED** [review]

**Comment by dangreen** [comment]
> Will nice if some words about changeset were in the contribution guide.

ooops

> Run `pnpm changeset` in the root of the repository and describe your changes. The resulting files should be committed as they will be used during release.

just now found it

**Comment by zkochan** [comment]
There is https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr

I copied that text about changesets from CONTRIBUTING.

of course, we can add more info, and duplicate it in the PR template.

**Pull request merged**
