### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by JustFly1984**
Work in progress. Upgrading typescript@5.4.2, uodating dependencies, improving types, improving eslint

### CODE REVIEW

**Comment by zkochan** [comment]
Don't reformat the code.

**Comment by zkochan** [comment]
We won't merge any refactoring to the v8 branch. That's for sure. Also, don't create a PR with so many changes. Formatting changes won't be merged. Other improvements that are not related to formatting changes can be discussed but in smaller PRs.

**Comment by JustFly1984** [comment]
@zkochan What is your main working branch?
Sorry for reformatting, I'm mostly refactoring it for myself, bulletproofing it. and learning pnpm on the way.
I've tried to do the same with yarn and npm-cli itself, but their codebase in much worse condition.
I'm not considering you to merge it at this point, I just want to be able to diff v8 against your current working branch, to see changes later.
I want to reduce an amount of packages to just one.

**Comment by zkochan** [comment]
"main" is the main working branch.

**Comment by moekhalil** [comment]
In reply to @JustFly1984 :
> @zkochan What is your main working branch? Sorry for reformatting, I'm mostly refactoring it for myself, bulletproofing it. and learning pnpm on the way. I've tried to do the same with yarn and npm-cli itself, but their codebase in much worse condition. I'm not considering you to merge it at this point, I just want to be able to diff v8 against your current working branch, to see changes later. I want to reduce an amount of packages to just one.

FYI, if your interested in understanding more about pull requests, and how to make them more readable for others, you can start [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) , [or here](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). For best practices [check this out](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests) and [this as well](https://www.metridev.com/metrics/pull-requests-best-practices-and-tips/)

Some suggestions: 

1.  You can create pull requests in your own fork if you wish to for testing or visibility. [This link does just that](https://github.com/JustFly1984/pnpm/compare/v8...JustFly1984:pnpm:main) and compares your main to pnpm/v8, as well as keeps the pull request only on your copy/fork of the repo. 

2.  **You can view the differences across branches without a pull request.** 😄  If you clone the branch locally (using `git clone https://github.com/pnpm/pnpm.git`), you can go into folder and just use `git diff remotes/origin/main remotes/origin/v8` to compare the branches, or if you `git pull origin/v8` after the clone, you can just do `git diff main v8` to clone the local copies of the branches, You can also export that diff to a file `git diff remotes/origin/main remotes/origin/v8 > main-vs-v8.diff` and open it with a text-editor/diff-viewer. No need for a pull request. 

3.  Lastly, regarding the "upgrade" to typescript (besides having a more specific title and description), if you were to create a pull request similar to it, you should only commit code changes *required* for the upgrade, or _relating to pull request_. That way reviewers can easily follow along and review the changes, and ensure when the pull request is merged, it only effects related areas. _**That way if something goes wrong, it's easier to figure out what pull request was likely the cause.**_

**Side note:** Large format changes should be avoided. Code is formatted using linters/tools before they are committed and if a team ever decides they wish to change the rules and reformat, a big manual PR is probably not the best way. **In my opinion**, it would be best to update the lint/rules, and create a GitHub action that applies the formatting to the code and creates a pull request for all to review. That way, since the large diff is coming from the GitHub Action, team members can be certain no code changes unrelated to the formatting was "snuck in".

**Pull request closed without merging**
