### PR TITLE
fix: remove the corresponding overrides package after remove package

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Comment by zkochan** [comment]
Why should the remove command remove overrides? What if they override subdependencies?

**Comment by btea** [comment]
For example, when I configure the following:
```js
pnpm: {
  overrides: {
    vite: "link:G:/vite/packages/vite"
  }
}
```
After I execute `pnpm i`, the corresponding package address in the devDependencies field will also become `link: G:/vite/packages/vite`. Therefore, I think the corresponding overrides should also be removed after the remove package.

**Comment by btea** [comment]
Maybe I should judge whether overrides is a link address? 🤔

**Comment by zkochan** [comment]
But overrides are overriding subdependencies as well. It is actually their main purpose. So even if you remove vite from direct dependencies, it may still be in the subdependencies.

**Comment by btea** [comment]
I generally use overrides to debug and verify the link code. So after the debugging is done, I will remove the corresponding linked package and install the released version. But as you said, `it may still be in the subdependencies.`, when I execute `pnpm i vite` after I remove it, the linked package will still be installed instead of the released version. So I created this pr.

**Comment by zkochan** [comment]
The remove command is for removing dependencies not for removing overrides. This is unexpected behaviour.

**Comment by btea** [comment]
Ok, I get it, feel free to close this pr.

**Pull request closed without merging**
