### PR TITLE
feat: fix regression regarding private git repo

### PR DESCRIPTION
**Pull request by KSXGitHub**
fixes https://github.com/pnpm/pnpm/issues/6827

We may need e2e tests for git repo to prevent further regression in the future.

Related PR that caused a regression: https://github.com/pnpm/pnpm/pull/6806

### CODE REVIEW

**Comment by KSXGitHub** [comment]
This would unfix https://github.com/pnpm/pnpm/issues/6805

**Comment by zkochan** [comment]
Why do you remove tarball resolution altogether? It is faster than fetching via git. And it worked before #6806

**Comment by KSXGitHub** [comment]
> And it worked before #6806

Because it wasn't even called.

But if you want to keep it, I guess we can try falling to clone, but I don't know the relevant code. Can you give me the location?

**Comment by marschr** [comment]
> Why do you remove tarball resolution altogether? It is faster than fetching via git. And it worked before #6806

I couldn't find my issue exactly, so I've looked into the `pnpm` code  and got no way of triggering the This is more like and RFC:
I'm having issues with tarballs and dependencies that need submodules and wasm/emscripten code to be build with the 
`prepare` script on `package.json`.
The issue is that with `npm` I can add a git dependency and it'll be fetched using a shallow git clone, creating the .git folder and working correctly with the submodules but with `pnpm` it always resolves to downloading the tar.gz file without the git repo information.
I've tried with all the `git+` combinations and all of them resolved to the tar.gz on public repos, I haven't tried using a private repo with `git+ssh` neither I've tried to clone from a local git server or a non popular git hosting server (i.e. not github, gitlab, etc) that may not support tar.gz packaging because the dependencies are open source. And as the `pnpm` code suggests, it never reaches the code from:
https://github.com/pnpm/pnpm/blob/0bc7a3f7469c2d3038a605bb340e30d2b273e7a8/fetching/git-fetcher/src/index.ts#L29

I know that fetching the tarball is much faster than even `git cloning --depth 1` all the deps, which is fine for all the other dependencies, so my question is: Is there a way to trigger a shallow clone from public repos instead of tarballs?

**Pull request closed without merging**
