### PR TITLE
fix: missing auth token in registries with paths included

### LINKED ISSUE #2933: Cannot authenticate to Github repo during the installation process
When trying to install my packages using a private registry, `pnpm` goes in error.
I think I know what's going on.

Doing the same via `npm` works fine because it installs the dependencies that are not in scope from the npm registry and installs the scoped dependencies (the private ones) from the github registry. I could verifying it by checking its `package-lock.json`

On the other hand, `pnpm` tries to install ALL the dependencies from one single registry, which is github.

### Code to reproduce the issue:

Code inside `.npmrc`

```
registry=https://npm.pkg.github.com/{SCOPE}
```

I can't give the information of the log because it contains sensitive information.

### Expected behavior:

It should install all the packages.

### Actual behavior:

```
 ERROR  GET https://npm.pkg.github.com/{SCOPE}/bootstrap: Unauthorized - 401
No authorization header was set for the request.

These authorization settings were found:
//npm.pkg.github.com/:_authToken={TOKEN}
```

### Additional information:

Changing `.npmrc` to the following works fine

```
{SCOPE}:registry=https://npm.pkg.github.com/{SCOPE}
```

### LINKED ISSUE #5970: Cannot authenticate to private registry during the installation process
It doesn't work only on macOS. I tried to reproduce issue on windows and it works fine.

Try to do `pnpm import` or `pnpm i`
### Code to reproduce the issue:
Code inside .npmrc
```
//artifactory.{name}.xyz/artifactory/api/npm/npm/:_authToken=[token]
always-auth=true
registry=https://artifactory.{name}.xyz/artifactory/api/npm/npm/
```
### Expected behavior:
Should install all packages

### Actual behavior:
```
 ERR_PNPM_FETCH_401  GET https://artifactory.{NAME}.xyz:443/artifactory/api/npm/npm/{SCOPE}/platform-jest-6.36.0.tgz: Unauthorized - 401
```
### Additional information:

 - `node -v` prints: v16.13.1
 - Windows, macOS, or Linux?: macOS Ventura 13.0.1

### PR DESCRIPTION
**Pull request by nachoaldamav**
close #5970 
close #2933

### CODE REVIEW

**Comment by dparish** [comment]
I still see this with GitHub private repos.

~/.npmrc
```
//npm.pkg.github.com:443/:_authToken=ghp_BLAHBLAH
```

And in my ppm project's root directory I have a .npmrc with:

```
@org:registry=https://npm.pkg.github.com:443/
```
where @org is my org

I've tried every combination of trailing slashes, 443's etc all to no avail.

```
pnpm --version
8.12.0
```

```
node --version
v20.3.1
```

**Comment by nachoaldamav** [comment]
Hi @dparish, I'll check it today.

**Comment by nachoaldamav** [comment]
@dparish I just tested it myself and it works for me, even with the port specified, what's the error you have?
```txt
//npm.pkg.github.com:443/:_authToken=<TOKEN>
@nachoaldamav:registry=https://npm.pkg.github.com:443/
```

**Comment by dparish** [comment]
```
 ERR_PNPM_FETCH_401  GET https://npm.pkg.github.com/@myorg%2Fswdk: Unauthorized - 401

This error happened while installing a direct dependency of ...

An authorization header was used: Bearer ghp_[hidden]

These authorization settings were found:
//npm.pkg.github.com/:_authToken=ghp_[hidden]
//registry.npmjs.org/:_authToken=npm_[hidden]
@myorg:registry=https://npm.pkg.github.com/
Progress: resolved 36, reused 35, downloaded 0, added 0
```

I'm not sure if this helps as I doubt it's related but:

I'm on Mac OS 14.1

```
uname -a
Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64
```

**Pull request merged**
