### PR TITLE
perf: accept gzip, deflate encoding from the registry

### PR DESCRIPTION
**Pull request by zkochan**
ref #3738

### CODE REVIEW

**Comment by juanpicado** [comment]
Interesting 🤔 need to check on my side

**Comment by zkochan** [comment]
Hopefully, I did everything right. I do not see significant performance improvements though.

I am trying to debug it with Fiddler but for some reason it doesn't show me the requests.

**Comment by umireon** [comment]
@zkochan It seems that Accept-Encoding does not work on the npm registry.
The response headers should include Content-Encoding but the actual is missing and the payload is plaintext.

スクリーンショット 2021-09-04 23 28 01

スクリーンショット 2021-09-04 23 28 31

スクリーンショット 2021-09-04 23 28 58

**Comment by zkochan** [comment]
I tested it with postman and with postman there was an almost 4x speed improvement on individual requests.

**Comment by umireon** [comment]
`Accept: application/vnd.npm.install-v1+json; q=1.0` disables gzip compression.

```
curl -fsSL --verbose --include -H 'Accept-Encoding: gzip,deflate' --http1.1 -o out.bin -H 'user-agent: pnpm/6.14.6 npm/? node/v16.8.0 darwin x64' -H 'accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8' -H 'connection: keep-alive' --raw https://registry.npmjs.org/@types%2Fnode
```

```
curl -fsSL --verbose --include -H 'Accept-Encoding: gzip,deflate' --http1.1 -o out2.bin -H 'user-agent: pnpm/6.14.6 npm/? node/v16.8.0 darwin x64' -H 'accept: application/json; q=0.8' -H 'connection: keep-alive' https://registry.npmjs.org/@types%2Fnode
```

**Comment by zkochan** [comment]
I see, maybe we can add it anyway. If the registry will be fixed, pnpm will become faster.

**Review by umireon — APPROVED** [review]

**Comment by shellscape** [comment]
Food.for thought: does GitHub Packages registry honor gziping?

**Comment by merceyz** [comment]
> `Accept: application/vnd.npm.install-v1+json; q=1.0` disables gzip compression.
> https://github.com/pnpm/pnpm/pull/3745#issuecomment-912991674

I sent a support request to npm about that months ago but was told `we'll get back to you shortly` and haven't heard anything since

**Comment by umireon** [comment]
@merceyz npm probably uses CloudFlare and it does not support such a mime type for gzipping.

https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-

**Comment by merceyz** [comment]
They do and indeed it doesn't, was hoping npm would enable it on their side. I see it was reported to them three years ago https://github.com/npm/registry-issue-archive/issues/365 but they haven't done it yet.

**Pull request merged**
