### PR TITLE
refactor: improve package-json reader

### PR DESCRIPTION
**Pull request by anonrig**
`load-json-file` implementation uses file-system operation, textdecoder and JSON.parse. We can omit having a dependency and at the same time improve the performance.

### CODE REVIEW

**Comment by anonrig** [comment]
Actually it seems like this package is used across all dependencies of pnpm. I'll change them all and run a benchmark to see the difference. Please do not merge this. @zkochan

**Comment by anonrig** [comment]
Any idea how I can run benchmarks in pnpm?

**Comment by anonrig** [comment]
A quick benchmark shows that `JSON.parse(await fs.readFile(path))` is 7% faster than `load-json-file`'s async version.

```
➜  benchmarks hyperfine 'node ./load-json-file.js' 'node ./native.js' --warmup 10
Benchmark 1: node ./load-json-file.js
  Time (mean ± σ):      30.3 ms ±   0.6 ms    [User: 23.8 ms, System: 5.4 ms]
  Range (min … max):    29.2 ms …  32.2 ms    90 runs

Benchmark 2: node ./native.js
  Time (mean ± σ):      28.4 ms ±   0.5 ms    [User: 22.2 ms, System: 5.1 ms]
  Range (min … max):    27.6 ms …  31.7 ms    96 runs

Summary
  node ./native.js ran
    1.07 ± 0.03 times faster than node ./load-json-file.js
```

**Comment by zkochan** [comment]
We can definitely replace it in `npm-resolver`, where we read the metadata files. Also, in package-requester, where read the index files. But for the `package.json` files I am not sure. We should probably check what npm CLI does. load-json-file strips  UTF-8 BOM https://github.com/sindresorhus/strip-bom, so we stop doing that, it might break for some users.

**Comment by zkochan** [comment]
Here's actually a related issue: https://github.com/pnpm/pnpm/issues/2629

so BOM is important

**Pull request closed without merging**
