### PR TITLE
feat(pnpm): add parameter --fail-if-no-match to get exit code as 1

### PR DESCRIPTION
**Pull request by Simon-He95**
close: #7403

### CODE REVIEW

**Comment by zkochan** [comment]
See my comments in the referenced issue.

**Comment by Simon-He95** [comment]
> See my comments in the referenced issue. [See my comments in the referenced issue.] 请参阅我在参考问题中的评论。[请参阅我在参考问题中的评论。

Okay, I will update this PR later

**Comment by Simon-He95** [comment]
> See my comments in the referenced issue.

Hi, zkochan. It’s just my first time to look at pnpm’s code and try pr. Can you help me check it?

**Comment by zkochan** [comment]
The changes are OK. But please also add a changeset.

Also, I am not entirely sure this flag name is good. Maybe we need a more specific one, like `--fail-if-no-match`

**Comment by Simon-He95** [comment]
I agree with what you said. It is indeed more accurate to use --fail-if-no-match. I have made some updates. Please help to check whether it is correct.

**Review by zkochan — APPROVED** [review]

**Pull request merged**
