### PR TITLE
feat: create pnpx for bundled pnpm

### PR DESCRIPTION
**Pull request by KSXGitHub**
Resolves https://github.com/pnpm/pnpm/issues/8230

### CODE REVIEW

**Comment by zkochan** [comment]
This will work. Alternatively, we could also just update the shell config files and add aliases. We already update the shell config files in order to extend the PATH env variable.

**Comment by KSXGitHub** [comment]
> we could also just update the shell config files and add aliases

It wouldn't work on Windows Command Prompt though. And I don't know how PowerShell's version of rc file works.

**Comment by KSXGitHub** [comment]
> we could also just update the shell config files and add aliases

Also, this definitely wouldn't work in CI environment.

**Comment by zkochan** [comment]
OK, add a comment about it to the function. Why this approach instead of aliases.

**Review by zkochan — APPROVED** [review]

**Pull request merged**
