### PR TITLE
feat: new plugin for managing Node.js versions

### PR DESCRIPTION
**Pull request by zkochan**
TODO:

- [x] add tests
- [x] select the right Node when running scripts
- [x] add a new option

***

`pnpm node [args...]` will autoinstall Node.js and run it.

If a project has `use-node-version` set in `.npmrc`, pnpm will auto-install the specified Node.js version and scripts will run using that version of Node.js

related discussion: https://github.com/pnpm/pnpm/discussions/3434

### CODE REVIEW

**Comment by zkochan** [comment]
I am using the `node-version` setting in `.npmrc` to detect which Node.js to run. Not sure if it is OK to reuse this setting. It is currently used by npm for another purpose:

> The node version to use when checking a package's engines setting.
ref https://docs.npmjs.com/cli/v7/using-npm/config#node-version

**Comment by zkochan** [comment]
[As noted](https://github.com/pnpm/pnpm/discussions/3434#discussioncomment-752975) by @woss, installing Node.js from the npm registry is not the best solution but it is much faster to implement.

In the future we'll use https://nodejs.org/download/release/index.json to resolve the version of Node.js and download Node.js from the nodejs org, not from the npm registry.

**Comment by Aankhen** [comment]
This is probably feature creep but it would be nice to support [fnm](https://github.com/Schniz/fnm), which runs on Windows as well as everywhere else.

**Comment by zkochan** [comment]
@Aankhen do you mean storing the node.js versions in the same place where they are store by fnm?

**Comment by Aankhen** [comment]
Sorry, between the name and GitHub having trouble rendering some of the files, I misunderstood what this plugin was doing! I’ve looked again and I see it’s unrelated to the script nvm. Apologies! Please carry on. 😳

**Comment by zkochan** [comment]
I am going to merge it and release a prerelease for now. If anyone will have comments, I'll make the changes.

cc @pnpm/collaborators

**Comment by woss** [comment]
> I am going to merge it and release a prerelease for now. If anyone will have comments, I'll make the changes.
> 
> cc @pnpm/collaborators

the link for collaborators ^^ is not working, is it because it's private?

**Comment by zkochan** [comment]
I published this change as `6.5.0-1`

**Comment by zkochan** [comment]
>the link for collaborators ^^ is not working, is it because it's private?

I don't know why, the collaborators team is set to visible. In any case, we don't do any discussions in private.

**Comment by Bessonov** [comment]
Does it read `engines.node` from package.json? I didn't find it in the code. If not, it's planned?

Related feature request for `engnes.pnpm`: https://github.com/pnpm/pnpm/issues/1383 .

**Comment by zkochan** [comment]
No, it does not read that field.

**Pull request merged**
