### PR TITLE
fix(plugin-commands-publishing): should pack main file or bin files defined in publishConfig

### LINKED ISSUE #4195: Original `main` file included in published package when using `publishConfig.main`
When using `publishConfig.main`, it is expected that the original `package.json#main` file not be included with the published package, but both `package.json#main` and `package.json#publishConfig#main` are included in the final tarball.

### Code to reproduce the issue:

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.ts",
  "publishConfig": {
    "main": "index.js"
  },
  "files": [
    "index.js"
  ]
}
```
```bash
$ pnpm publish --dry-run
```

### Expected behavior:

```bash
test $ pnpm publish --dry-run
npm notice 
npm notice 📦  test@1.0.0
npm notice === Tarball Contents === 
npm notice 0B   index.js    
npm notice 146B package.json
npm notice === Tarball Details === 
npm notice name:          test                                    
npm notice version:       1.0.0                                   
npm notice filename:      test-1.0.0.tgz                          
npm notice package size:  215 B                                   
npm notice unpacked size: 146 B                                   
npm notice shasum:        e8eb81c73d443997932b32e2053f9421084057fd
npm notice integrity:     sha512-jJXoLwzxxTW4M[...]KYv+hLJf40fHg==
npm notice total files:   2                                       
npm notice 
+ test@1.0.0
```

### Actual behavior:

```bash
test $ pnpm publish --dry-run
npm notice 
npm notice 📦  test@1.0.0
npm notice === Tarball Contents === 
npm notice 0B   index.js    
npm notice 0B   index.ts                       <--- should not be included!
npm notice 146B package.json
npm notice === Tarball Details === 
npm notice name:          test                                    
npm notice version:       1.0.0                                   
npm notice filename:      test-1.0.0.tgz                          
npm notice package size:  228 B                                   
npm notice unpacked size: 146 B                                   
npm notice shasum:        06ffa8fdb20a358c1a019d732fe9deda672742a0
npm notice integrity:     sha512-IcNX54PNvFF+U[...]2E0kSIKPxzr8Q==
npm notice total files:   3                                       
npm notice 
+ test@1.0.0
```

### Additional information:

`npm-packlist`, as used [here](https://github.com/pnpm/pnpm/blob/main/packages/plugin-commands-publishing/src/pack.ts#L90), includes `main` by [default](https://github.com/npm/npm-packlist/blob/main/index.js#L171), so specifically ignoring `index.ts` in this example via `package.json#files` (or `.npmignore`) doesn't help. 

One approach may be to generate [`publishManifest`](https://github.com/pnpm/pnpm/blob/3d6ebd6dbfc2d081fd0fcdc21027c9b1ae142e3d/packages/plugin-commands-publishing/src/pack.ts#L129) *before* adding the packaged files to specifically enable filtering of `package.json#main` in cases where it is overridden by `package.json#publishConfig#main`. I suspect, however, that replacing `package.json` on disk with the generated `exportableManifest` before calling `npm-packlist` would also be an option, and may simplify additional `publishConfig` edge-case handling.

 - `node -v` prints: v17.3.0
 - Windows, macOS, or Linux?: macOS

### PR DESCRIPTION
**Pull request by await-ovo**
fix #4195 

Following @popeindustries's  suggestion,  we can create publishManifest before pack tarball, and then use the [`packageJsonCache` option in npm-packlist](https://github.com/npm/npm-packlist/blob/v5.1.3/lib/index.js#L211) to avoid loading pacakge.json from the local filesystem, which should ensure that the final list of files in packed tarball is the one that needs to be published.

### CODE REVIEW

**Review by zkochan — APPROVED** [review]

**Comment by snicol21** [comment]
I believe this appears to have broken our build

I've been using [clean-package](https://www.npmjs.com/package/clean-package) in conjunction with pnpm for my builds.

our pnpm pack used to generate a structure that looked like this:

.
└── package/
    └── dist/
        └── ...
    
but since this patch went in 13 hrs ago it started including a single index.ts file within the published package

.
└── package/
    ├── dist/
    │   └── ...
    └── src/
        └── index.ts
        
which is now breaking all consumers of our packages.

**Comment by await-ovo** [comment]
@snicol21 Hi, can you provide a repository that reproduces the above problem?

**Comment by snicol21** [comment]
> @snicol21 Hi, can you provide a repository that reproduces the above problem?

Thanks @await-ovo , here's a quick repo I put together and was able to recreate the issue. I added some details to the README.md

https://github.com/snicol21/my-ts-pnpm

**Comment by await-ovo** [comment]
> > @snicol21 Hi, can you provide a repository that reproduces the above problem?
> 
> Thanks @await-ovo , here's a quick repo I put together and was able to recreate the issue. I added some details to the README.md
> 
> https://github.com/snicol21/my-ts-pnpm

Thanks for the detailed steps to reproduce the problem, I think I know what the problem is, I'll send a pr to fix this later ~

**Comment by snicol21** [comment]
> > > @snicol21 Hi, can you provide a repository that reproduces the above problem?
> 
> > 
> 
> > Thanks @await-ovo , here's a quick repo I put together and was able to recreate the issue. I added some details to the README.md
> 
> > 
> 
> > https://github.com/snicol21/my-ts-pnpm
> 
> 
> 
> Thanks for the detailed steps to reproduce the problem, I think I know what the problem is, I'll send a pr to fix this later ~

Awesome! Thanks for your help.

**Pull request merged**
