### PR TITLE
feat(exec): log prefix

### PR DESCRIPTION
**Pull request by KSXGitHub**
Fixes https://github.com/pnpm/pnpm/issues/8065

### CODE REVIEW

**Comment by zkochan** [comment]
Is this an opt-in new feature? Could you add a changeset?

**Review by zkochan — APPROVED** [review]

**Comment by lukasIO** [comment]
Hi, this change introduced an issue where CI runs are breaking for us that rely on the --json output of a command.

Previously, I was under the impression, that when you add --filter=package-name this would lead to the prefix being omitted, but looks like this was a wrong assumption?

Is there any way to force the prefix to be omitted in order to be able to parse/pipe the output ?

**Comment by KSXGitHub** [comment]
@lukasIO It's been fixed in https://github.com/pnpm/pnpm/pull/8176

> Is there any way to force the prefix to be omitted in order to be able to parse/pipe the output ?

Add `--reporter-hide-prefix` to the command line or add `reporter-hide-prefix=true` to `.npmrc`.

**Comment by lukasIO** [comment]
got it, thanks!

**Pull request merged**
