### PR TITLE
fix: run `node-gyp rebuild` when a project has a `binding.gyp` file

### PR DESCRIPTION
**Pull request by syi0808**
checkBindingGyp was called only within buildDependency. I don't know exactly, but because of that, checkBindingGyp didn't explore if the chunks weren't circulating inside [buildModules](https://github.com/pnpm/pnpm/blob/b0e8ae8761d00120b5aef6cd5a7c14d1599644f1/exec/build-modules/src/index.ts#L67).

I've changed this to check unconditionally before install script is executed. But I'm not sure if this is the correct fix. If you give me your opinion, I'll reflect on the test as well.

Fix: #8293

### CODE REVIEW

**Comment by zkochan** [comment]
I believe the fix should happen in the `runLifecycleHooksConcurrently` function. You can see in that function the scripts is checked but for node-gyp the scripts part is optional. That is why it doesn't work.

**Comment by syi0808** [comment]
> I believe the fix should happen in the `runLifecycleHooksConcurrently` function. You can see in that function the scripts is checked but for node-gyp the scripts part is optional. That is why it doesn't work.

I've moved this logic into `runLifeCycleHooksConcurrently`.

**Comment by syi0808** [comment]
checkBindingGyp is only called inside the buildDependency. regardless of whether there was a module to build in the project or not, I think I should check binding.gyp.

**Comment by syi0808** [comment]
I modified the test. I also made very small changes to the implementation so that the existing test would not be broken.

**Review by zkochan — APPROVED** [review]

**Pull request merged**
