### PR TITLE
fix(git-resolver): handle private git repo resolution

### PR DESCRIPTION
**Pull request by Utsav2**
In the case where:

1. No git auth token was specified by the user
2. The package requested to be fetched via https
3. The user does not have SSH access to the repo but has HTTPS access
4. The package was hosted in a private GitHub repo

pnpm would fallback to using SSH since it was a "likely private repo" and would fail to resolve the package. Now, rather than only checking if there is an auth token specified, it also checks both:

1. Is the repo private
2. Does the user have access to ls-remote it.

And if these conditions are true, it tries to use https anyway.

This matches the behavior of npm and Yarn berry. Yarn classic also has this bug, and there's a code comment that alludes to it.

### CODE REVIEW

**Comment by zkochan** [comment]
Spellcheck failed. You can add cspell ignore comments to fix the issue.

**Comment by Utsav2** [comment]
> Spellcheck failed. You can add cspell ignore comments to fix the issue.

added. I could add a changelog entry if you think it'll be useful for this change.

**Comment by Mister-Hope** [comment]
I agree that this pr does fix some edge case bugs, but I think this might not be a nice approach.

The isRepoPublic has 0 retries, which means as long as one attempt fails in any cases, it will be reverted to ssh permanently, and even with a reinstall with lockfile removed (I guess because of `.modules yaml` in `node_modules` )

Also I believe there might be a bug here as `pnpm up` always (or most time) convert any https to ssh, not sure the reason behind, and this also happens on my hostwinds server, which proves this is not my local network issue.

**Comment by Mister-Hope** [comment]
See https://github.com/pnpm/pnpm/issues/7517#issuecomment-2817737427

I did some debug earlier, this probably need to be handled more gracefuly

**Pull request merged**
