### PR TITLE
add prettier plugins to default public hoist patterns

### PR DESCRIPTION
**Pull request by jonathanmorley**

### CODE REVIEW

**Comment by zkochan** [comment]
I did not notice issues with prettier. What are the steps to repro the issues?

**Comment by jonathanmorley** [comment]
Prettier itself is fine, but my repo steps are:

**Comment by jonathanmorley** [comment]
i was considering adding `@prettier/plugin-*` and `*prettier-plugin-*` to the list, but went with the broader option you see in the commit because of the existing broad-looking globs

I'm fine with either approach, they would both catch prettier plugins according to the patterns listed on https://prettier.io/docs/en/plugins.html

**Comment by zkochan** [comment]
I think if `@prettier/plugin-*` and `*prettier-plugin-*` are fixing the issue, probably they should be used instead.

**Pull request merged**
