### PR TITLE
fix: link global

### LINKED ISSUE #4761: pnpm link --global for a dependency with a bin prints unexpected warning
pnpm version 7.1.1

Take a project with a simple file at `bin/command.mjs`

```js
#!/usr/bin/env node

console.log("hello world");
```

Configure it via the `bin` field of that project's `package.json` file.

```json
  "bin": { "myCommand": "./bin/command.mjs" }
```

Install this local project globally.

```js
pnpm link --global
```

Unexpected output:

```
 WARN  undefined has no binaries
```

The associated bin file is available as expected despite this warning.

### PR DESCRIPTION
**Pull request by spencer17x**
close #4761

### CODE REVIEW

**Comment by Spencer17x** [comment]
@zkochan Please help review it

**Comment by zkochan** [comment]
I need to investigate this because I am not sure currently where this fix should be.

**Comment by spencer17x** [comment]
> I need to investigate this because I am not sure currently where this fix should be.

Is this pr still needed？

**Comment by dribble-njr** [comment]
If it can't work, please close it @zkochan .

**Comment by mblouka** [comment]
This PR fixes the issue on my end. Why isn't it pushed yet? It has been two years.

**Comment by zkochan** [comment]
This should solve it: https://github.com/pnpm/pnpm/pull/7637

**Pull request closed without merging**
