### PR TITLE
fix: avoid property 'requiresBuild' of undefined error

### PR DESCRIPTION
**Pull request by zkochan**
ref #1217

### CODE REVIEW

**Comment by zkochan** [comment]
@pgonzal please review

**Comment by pgonzal** [comment]
Thanks!  Tonight I will test this with my project that repros the issue, and see if the problem is fixed.

BTW do you expect this to also fix the issue where 2.4.0 was installing two copies of everything?

**Comment by pgonzal** [comment]
This eliminates the crash, so PNPM does produce a valid shrinkwrap.yaml file.  However the counter is still showing twice the number of packages getting installed.

**Comment by zkochan** [comment]
Review updated. I managed to find the core of the issue and fixed it.

> BTW do you expect this to also fix the issue where 2.4.0 was installing two copies of everything?

That seems like only a reporting issue. I'll check that later, separately.

**Comment by pgonzal** [comment]
Thanks very much for getting this fixed so quickly!

**Pull request merged**
