### PR TITLE
feat(git-resolver): fix private git repo

### PR DESCRIPTION
**Pull request by KSXGitHub**
fixes https://github.com/pnpm/pnpm/issues/6827
closes https://github.com/pnpm/pnpm/pull/6829

### CODE REVIEW

**Comment by zkochan** [comment]
cover it with a test, please. Unit test is OK.

**Comment by zkochan** [comment]
there appears to be a conflict

**Comment by KSXGitHub** [comment]
@zkochan It was probably caused by the commit that reverses one of my fix yesterday.

**Review by zkochan — APPROVED** [review]

**Comment by KSXGitHub** [comment]
> `thrown: "Exceeded timeout of 240000 ms for a test.`

It guess it happens when I also push changes in the other branch.

**Pull request merged**
