### PR TITLE
Run local CLI, when available

### PR DESCRIPTION
**Pull request by zkochan**
When a CLI tool like gulp is used, if there is a local installation of it, the local installation is executed instead of the global one.

### CODE REVIEW

**Comment by iamstarkov** [comment]
does it make sense npm pnpm?

**Comment by zkochan** [comment]
I think this is the only solution to avoid bad DX. We have some hacks to make CLIs work without `--preserve-symlinks`. However, if we allow CLIs to execute the local instances of themselves, they will escape our hacks (which is setting the NODE_PATH env variable).

IMHO this solution also allows to add a pretty exciting feature to pnpm. We can make local CLIs available in the command line, when inside the package folder

**Comment by iamstarkov** [comment]
> IMHO this solution also allows to add a pretty exciting feature to pnpm. We can make local CLIs available in the command line, when inside the package folder

it does make sense for babel and eslint, but what is the pnpm use case?

**Comment by iamstarkov** [comment]
in order to use local package, you have to install it and global package is required for this

**Comment by zkochan** [comment]
I don't mean to install pnpm locally.

This PR is about changing the global package bin files. If a global package is executed, it checks first, whether there is a local installation of that package, if there is, the local installation is used.

**Comment by zkochan** [comment]
[This test](https://github.com/pnpm/pnpm/pull/571/files#diff-80c5b2e3b39645eea19bcf781462e975R681) demonstrates what I mean

**Comment by iamstarkov** [comment]
still dont get it

**Comment by iamstarkov** [comment]
do you mean if i have global and local `{cliPkg}` both installed by pnpm, so when i run global `{cliPkg}`, pnpm will make it to run local one?

**Comment by zkochan** [comment]
yes

**Comment by iamstarkov** [comment]
I though it is`{cliPkg}`s' responsibility to choose to handle this. eslint, babel, ava, gulp, etc are doing this and its explicitly stated in their documentation. Why do you want to implicitly force this choice on all cli tools?

**Comment by zkochan** [comment]
Because pnpm creates a special kind of cmd-shims that set the NODE_PATH env variable. Setting the NODE_PATH env variable is a workaround to allow tools like eslint find their plugins.

However, when tools like eslint execute the local instances of themselves, they omit the cmd-shims created in `.bin` and as a consequence, they won't work correctly.

IMHO, this solution is fine, as ied doesn't even support global packages and this solution allows to use them with our symlinked node_modules structure.

**Comment by andreypopp** [comment]
There's also security considerations we should take into account — the fact that a globally installed executable can be overriden by the one installed locally.

**Comment by zkochan** [comment]
Security is not the strong side of npm, I guess. But I added a console message that the local CLI is used.

Also, it overrides only commands from the same package.

**Comment by zkochan** [comment]
I see 3 types of packages:

1. packages used only globally. Nothing will be changed for them
2. packages used both globally and locally. They are mostly intended to be used this way anyway (like eslint, gulp, etc.)
3. packages that are used locally only. Nothing will be change for them.

So this makes even a better DX for packages from the 2nd group and changes nothing for the 1st and 3rd type of CLI packages.

**Comment by iamstarkov** [comment]
> So this makes even a better DX for packages from the 2nd group and changes nothing for the 1st and 3rd type of CLI packages.

as i said, what if i want my {cli}'s global and local instances to work separately? No OSS developer deserves to get issues because of pnpm implicitness in this case

**Comment by iamstarkov** [comment]
i think pnpm is great and you are doing great job developing it, so i dont want pnpm to get bad reputation just because incorrect assumption

**Comment by zkochan** [comment]
thanks. I don't take it personally. I just want to solve the problem. If you think this assumption might be not true for all the use cases, I can't prove that you are not right, so I should agree.

I think I can rewrite it so that the global CLI will be used with node_modules folders added from the local CLI's lookup. That should work as well

**Comment by iamstarkov** [comment]
i mean global to local linking should be on the package's shoulder as it is now. pnpm should just not breake it

**Comment by zkochan** [comment]
yeah, right, I agree.

**Pull request closed without merging**
