### PR TITLE
fix: reduce the side-effects cache key length

### LINKED ISSUE #5056: Invalid string length
image

when I run `pnpm i` second time, this error show

when I run `rm -rf /XXX/pnpm/store/v3` can fix it

### pnpm version:
7.5.2

### Additional information:
node -v
v16.14.0

macOS, Linux

### PR DESCRIPTION
**Pull request by zkochan**
close #5056

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]
FWIW it seems like https://www.npmjs.com/package/node-object-hash is 10x faster (if you can believe their benchmarks).

**Comment by jakebailey** [comment]
I can confirm that this PR fixes the test case I had for #5056.

image

Which is roughly:

```console
$ git clone https://github.com/DefinitelyTyped/DefinitelyTyped.git
$ git switch --detach c76c419153bf70858ab82843483657ae1bf11f17
$ pnpm install --filter . --filter '...[HEAD^1]...'
$ pnpm ls --depth Infinity --parseable --filter '...@types/**[HEAD^1]...'
```

(This goofy command is part of a workaround for #7283; unfortunately it can stil OOM but this PR has fixed more typical runs.)

**Comment by zkochan** [comment]
oh, ok

I'll use node-object-hash instead.

**Review by BlackHole1 — APPROVED** [review]
LGTM

**Comment by samtsai** [comment]
I'm still seeing this:
```
[2024-01-29T17:26:39.979Z] Removing intermediate container 69c5274b8d3e
[2024-01-29T17:26:39.979Z]  ---> d64ca7992607
[2024-01-29T17:26:39.979Z] Step 11/12 : COPY package.json ./
[2024-01-29T17:26:39.979Z]  ---> 2a9e8f66a8ea
[2024-01-29T17:26:39.979Z] Step 12/12 : RUN pnpm install -r --offline
[2024-01-29T17:26:39.979Z]  ---> Running in 2806c668ddea
[2024-01-29T17:26:47.860Z] .../esbuild@0.20.0/node_modules/esbuild postinstall$ node install.js
[2024-01-29T17:26:47.860Z] .../esbuild@0.19.12/node_modules/esbuild postinstall$ node install.js
[2024-01-29T17:26:47.860Z] .../esbuild@0.20.0/node_modules/esbuild postinstall: Done
[2024-01-29T17:26:47.860Z] .../esbuild@0.19.12/node_modules/esbuild postinstall: Done
[2024-01-29T17:28:02.158Z]  ERROR  Invalid string length
[2024-01-29T17:28:02.158Z] 
[2024-01-29T17:28:02.158Z] RangeError: Invalid string length
[2024-01-29T17:28:02.158Z]     at Array.join (<anonymous>)
[2024-01-29T17:28:02.158Z]     at Array.toString (<anonymous>)
[2024-01-29T17:28:02.158Z]     at Object._object (/home/builder/.cache/node/corepack/pnpm/8.15.0/dist/pnpm.cjs:124428:29)
[2024-01-29T17:28:02.158Z]     at objectToString (/home/builder/.cache/node/corepack/pnpm/8.15.0/dist/pnpm.cjs:124574:61)
[2024-01-29T17:28:02.158Z]     at hash (/home/builder/.cache/node/corepack/pnpm/8.15.0/dist/pnpm.cjs:124597:24)
[2024-01-29T17:28:02.158Z]     at calcDepState (/home/builder/.cache/node/corepack/pnpm/8.15.0/dist/pnpm.cjs:124639:76)
[2024-01-29T17:28:02.158Z]     at /home/builder/.cache/node/corepack/pnpm/8.15.0/dist/pnpm.cjs:126132:69
[2024-01-29T17:28:02.263Z] The command '/bin/sh -c pnpm install -r --offline' returned a non-zero code: 1
```

**Comment by jakebailey** [comment]
Reading https://github.com/SkeLLLa/node-object-hash/blob/master/src/stringifiers.ts#L392, it looks like this library builds up a hash by building a huge string representation and then hashing it... which was what we were already attempting to avoid... (Related is https://github.com/SkeLLLa/node-object-hash/issues/63#issuecomment-1715637080, which is the same root cause; building up huge strings).

I guess my suggestion for a "faster" library was not a good one, because it looks like `object-hash` avoids this problem by streaming the hash updates: https://github.com/puleos/object-hash/blob/master/index.js#L173

**Comment by zkochan** [comment]
Ok, let's switch to object-hash then

**Comment by jakebailey** [comment]
Sent https://github.com/pnpm/pnpm/pull/7591.

**Pull request merged**
