### PR TITLE
feat(recursive): new option for continuing execution on task fails

### PR DESCRIPTION
**Pull request by zkochan**
TODO:

- [x] support `pnpm recursive exec`
- [x] support `pnpm recursive run`
- [x] support `pnpm recursive test`
- [x] support `pnpm recursive rebuild`

### CODE REVIEW

**Comment by zkochan** [comment]
@vjpr I used the flag name `--no-bail` (like in lerna) but I don't know if that is a good name. Is there some standard name for such flags?

`npm-run-all` uses `--continue-on-error` which I like more as it is more explicit.

Also, I did it so that all tasks will finish but if at least one failed, pnpm will exit with a non-zero exit code, which seems like expected to me.

**Comment by zkochan** [comment]
Probably it would be useful to print a summary of failed packages in the end. Something like:

```
Summary: 2 failed, 6 completed

x /packages/foo:
  ERROR ....

x /packages/bar:
  ERROR ...
```

**Comment by vjpr** [comment]
I like `--continue-on-error`.

---

`gcc` uses `-Wfatal-errors`, but this is ugly.

**Comment by zkochan** [comment]
I've seen also somewhere the flag `--fast-fail`
it would be `--no-fast-fail` then

**Comment by zkochan** [comment]
@vjpr seems like `--bail` is also used by jest and mocha, so it is more widely used. I would stick with it

**Comment by zkochan** [comment]
merged

**Comment by zkochan** [comment]
:ship: [2.13.0](https://github.com/pnpm/pnpm/releases/tag/v2.13.0)

**Pull request closed without merging**
