### PR TITLE
fix: Gitlab resolver

### PR DESCRIPTION
**Pull request by datrhi**
fix https://github.com/pnpm/pnpm/issues/7603

### CODE REVIEW

**Comment by datrhi** [comment]
https://docs.gitlab.com/ee/api/repositories.html#get-file-archive
params is `sha` not `ref`

**Comment by zkochan** [comment]
You should make the fix in the package directly, not submit a patch to this repository

**Comment by datrhi** [comment]
> You should make the fix in the package directly, not submit a patch to this repository

Yes, sr for that
I made a PR for that repository: https://github.com/zkochan/hosted-git-info/pull/3

**Comment by zkochan** [comment]
replace `@zkochan/git-hosted-info` with `@pnpm/git-hosted-info`. I have published your fix.

**Comment by datrhi** [comment]
> replace `@zkochan/git-hosted-info` with `@pnpm/git-hosted-info`. I have published your fix.

I've just completed the update. Thanks a lot for the prompt assistance!

**Comment by zkochan** [comment]
add a changeset, please.

**Comment by datrhi** [comment]
> add a changeset, please.

sr I forgot it
added

**Review by zkochan — APPROVED** [review]

**Pull request merged**
