### PR TITLE
test: fix flaking filterProd and monorepo test due to json-append on windows

### PR DESCRIPTION
**Pull request by gluxon**
## Problem

Similar to https://github.com/pnpm/pnpm/pull/7346, I'm seeing this test in `test/filterProd.test.ts` flake on Windows.

```
2023-12-19T18:45:03.5114961Z FAIL test/filterProd.test.ts (6.17 s)
2023-12-19T18:45:03.5117704Z   ● --filter should include devDependencies
2023-12-19T18:45:03.5118205Z 
2023-12-19T18:45:03.5120054Z     expect(received).toStrictEqual(expected) // deep equality
2023-12-19T18:45:03.5120621Z 
2023-12-19T18:45:03.5120898Z     - Expected  - 1
2023-12-19T18:45:03.5121295Z     + Received  + 0
2023-12-19T18:45:03.5121553Z 
2023-12-19T18:45:03.5121686Z       Array [
2023-12-19T18:45:03.5123124Z         "project-1",
2023-12-19T18:45:03.5123926Z         "project-3",
2023-12-19T18:45:03.5124769Z     -   "project-4",
2023-12-19T18:45:03.5125159Z       ]
2023-12-19T18:45:03.5125351Z 
2023-12-19T18:45:03.5129028Z       54 |   await execPnpm(['recursive', 'test', filter, '...project-3'])
2023-12-19T18:45:03.5132391Z       55 |   const { default: output } = await import(path.resolve('output.json'))
2023-12-19T18:45:03.5134315Z     > 56 |   expect(output.sort()).toStrictEqual(expected)
2023-12-19T18:45:03.5135327Z          |                         ^
2023-12-19T18:45:03.5136097Z       57 | })
2023-12-19T18:45:03.5136621Z 
2023-12-19T18:45:03.5138194Z       at test/filterProd.test.ts:56:25
```

## Changes

Using the approach in https://github.com/pnpm/pnpm/pull/7346, let's write to separate files for testing to avoid race conditions when writing to the same file.

### CODE REVIEW

**Comment by gluxon** [comment]
Many other tests still use `json-append`, but it makes sense to keep those since they are checking for strict order (unlike the test edited in this PR).

https://github.com/pnpm/pnpm/blob/733d612ad1cf5399ec2ab2a41080c06862f21388/pnpm/test/monorepo/index.ts#L334

I searched the repo for other `json-append` usages. If I missed any tests that aren't comparing output using `toStrictEqual`, please give a heads up!

**Comment by gluxon** [comment]
While building the initial commit on this PR, I saw another flake.

```
2023-12-19T20:05:59.3289955Z   ● test-pattern is respected by the test script
2023-12-19T20:05:59.3290524Z 
2023-12-19T20:05:59.3290822Z     expect(received).toStrictEqual(expected) // deep equality
2023-12-19T20:05:59.3291237Z 
2023-12-19T20:05:59.3291427Z     - Expected  - 1
2023-12-19T20:05:59.3291702Z     + Received  + 0
2023-12-19T20:05:59.3291877Z 
2023-12-19T20:05:59.3292005Z       Array [
2023-12-19T20:05:59.3292334Z     -   "project-2",
2023-12-19T20:05:59.3292613Z         "project-4",
2023-12-19T20:05:59.3292835Z       ]
2023-12-19T20:05:59.3292945Z 
2023-12-19T20:05:59.3293018Z       406 |
2023-12-19T20:05:59.3293658Z       407 |   const { default: output } = await import(path.resolve('..', 'output.json'))
2023-12-19T20:05:59.3294410Z     > 408 |   expect(output.sort()).toStrictEqual(['project-2', 'project-4'])
2023-12-19T20:05:59.3295952Z           |                         ^
2023-12-19T20:05:59.3296419Z       409 | })
2023-12-19T20:05:59.3296636Z       410 |
2023-12-19T20:05:59.3297140Z       411 | test('changed-files-ignore-pattern is respected', async () => {
2023-12-19T20:05:59.3297638Z 
2023-12-19T20:05:59.3297875Z       at Object.<anonymous> (test/monorepo/index.ts:408:25)
```

Pushed up a fix for that one as well.

**Comment by zkochan** [comment]
Use sync fs operations in tests. I have updated the code.

Regarding your changes, I think now they test less as before your changes the order of execution was checked as well. Which is also important to verify. I guess the issue was that some packages can run at the same time. However, we still need to check that dependencies are built first.

**Comment by gluxon** [comment]
> Regarding your changes, I think now they test less as before your changes the order of execution was checked as well. Which is also important to verify. I guess the issue was that some packages can run at the same time. However, we still need to check that dependencies are built first.

I agree the issue is that some packages can run at the same time. Before my changes, the 2 tests edited in this PR attempted to handle this by sorting the output before comparing though. Since the `output.txt` file was sorted, I don't believe my changes regress what these tests are checking for?

Here's what both tests did before my changes:

https://github.com/pnpm/pnpm/blob/7cbfde36a0410da38a2e8721d676253f2f5d3a58/pnpm/test/monorepo/index.ts#L408

For example, even if `project-4` is supposed to run before `project-2` based on dependencies, the tests edited here just sort the output so it's always `['project-2', 'project-4']`.

I intentionally did not modify `json-append` for other tests that rely on topological script execution to avoid regressing what those tests checked for.

I think a good plan is:

1. If the tests check for script execution order → use `json-append`
2. If scripts can run in any order → use the trick in this PR to avoid race conditions

**Comment by gluxon** [comment]
One other idea I had was to replace all `json-append` tests with a unix socket, which has better FIFO guarantees without race conditions erasing the output of other scripts. All these tests need is a simple [FIFO pipe](https://man7.org/linux/man-pages/man7/fifo.7.html). A unix socket is a bit overkill for that, but FIFO pipes don't have great cross-platform support.

https://github.com/gluxon/pnpm/commits/test-echo-server/

I'm still playing around with the idea and might open a PR for it if I don't find any issues.

**Review by zkochan — APPROVED** [review]

**Comment by gluxon** [comment]
The IPC approach works well. Here's the PR for it: https://github.com/pnpm/pnpm/pull/7472

**Pull request merged**
