### PR TITLE
fix: audit output

### LINKED ISSUE #5981: New pnpm audit paths break reports
In pnpm 7.25 the path of the security vulnerability has been added to the output. If the path is very long it will break the whole report.

Please break the path after a max length or at every ">" into parts or shorten the path (only the first and the last one is important). 
Maybe just whitespace is missing around ">" as shown in #3073 example screenshot.

### pnpm version:

7.26.0

### Code to reproduce the issue:

pnpm add @graphql-codegen/near-operation-file-preset@2.4.4
pnpm audit

### Actual behavior:
Screenshot 2023-01-25 165044

### Additional information:

 - `node -v` prints: v18.12.0
 - Windows, macOS, or Linux?: Windows WSL2

### PR DESCRIPTION
**Pull request by pitgrap**
Add linebreaks to long dependency paths and titles in `pnpm audit` output for better readability. close #5981

### CODE REVIEW

**Comment by zkochan** [comment]
The package that renders the table can do text wrapping. See the "text wrapping" section in the end of the README: https://www.npmjs.com/package/@zkochan/table?activeTab=readme

**Comment by pitgrap** [comment]
Nice, that's even better. Will rework it

**Comment by pitgrap** [comment]
That's strange, why is the test output in CI different to the updated snapshots?

**Comment by pitgrap** [comment]
@zkochan, why do I get different results between running `pnpm run test-branch` in root folder and running `pnpm test` directly in `lockfile/plugin-commands-audit`? We could reproduce this on two different machines.

**Comment by zkochan** [comment]
I don't know why

**Comment by pitgrap** [comment]
Can you reproduce the different outputs?

**Comment by pitgrap** [comment]
with the latest commit `pnpm run test-branch` will work, but you cannot run the tests in the folder or via --filter anymore. 🤷‍♂️

**Review by zkochan — APPROVED** [review]

**Pull request merged**
